/**
 * English catalog — the single source of truth.
 *
 * Vorynth ships 10 bundled languages (en, fa, ar, ko, ja, zh, he, es, de, ru —
 * see `locales.ts` and the sibling `<code>.ts` catalogs, all type-checked
 * against this one). Any other language is a user-supplied translation: the
 * user exports this object as JSON, translates it in any editor, and imports
 * it back (see Profile → Language).
 *
 * Keys are namespaced by screen so adding a new screen is one block. The
 * flat-ish structure makes the exported JSON easy to translate by hand.
 */
export const en = {
	app: {
		name: "Vorynth",
		tagline: "Less reading. More understanding.",
		// Shown under the logo — reassures non-technical users that nothing
		// leaves the device, without "engine" jargon.
		localEngine: "Private & local",
	},
	nav: {
		brief: "Today's Brief",
		sources: "Sources",
		media: "Media",
		profile: "Profile",
		settings: "Settings",
		generate: "Generate Brief",
		user: "Local User",
		archive: "Archive",
		docs: "Docs",
		changelog: "Changelog",
		openProfile: "Open profile",
		openSettings: "Open settings",
		history: "History",
		openHistory: "Open history",
		docsPages: "Pages",
		docsTransparency: "Transparency",
		docsExpand: "Expand Docs sections",
		docsCollapse: "Collapse Docs sections",
		jobsActive_one: "{{count}} job",
		jobsActive_other: "{{count}} jobs",
		items: "Items",
		collections: "Collections",
		bookmarks: "Bookmarks",
		search: "Search",
		trash: "Trash",
		archiveSections: "Archive sections",
	},
	brief: {
		title: "Today's Intelligence Brief",
		timer: "10-minute briefing",
		stories: "{{count}} stories",
		sources: "{{count}} sources",
		intelligenceOn: "Intelligence mode — AI enrichment active",
		newsMode: "News mode — ranked by freshness & reliability",
		domains: "Domains",
		importance: "Importance",
		all: "All",
		// v1.8.0 — Brief / History tabs (History = story-view history).
		briefTab: "Brief",
		historyTab: "History",
		loadMore: "Load more stories",
		empty: {
			title: "No stories yet",
			body: "Vorynth is ready to collect. Hit Collect to pull the latest from your sources — no API key required.",
			collect: "Collect Now",
			working: "Working…",
		},
		readOn: "Read on {{source}}",
		newsHint:
			"<strong>News mode.</strong> Switch to Intelligence mode in <0>Settings</0> when your provider is ready.",
		intelligenceActive: "Intelligence Mode Active",
		savedStories: "Saved stories",
		resetFilters: "Reset filters to defaults",
		clear: "Clear",
		emptyRangeTitle: "No stories in this range",
		emptyRangeBody:
			"Either no articles have been collected yet, or none fall in the selected period. Hit <em>Collect</em> to pull fresh stories — no API key required.",
	},
	storyViews: {
		title: "Viewed stories",
		subtitle:
			"Stories you opened, and whether you saw the insight, the article, or both in one sitting.",
		empty:
			"Stories you open will show here — view a story's insight or its article and it gets recorded.",
		scopeInsight: "Insight",
		scopeArticle: "Article",
		scopeBoth: "Insight + article",
	},
	why: "Why it matters",
	impact: "Impact",
	recommendedAction: "Takeaway",
	sourcesLabel: "Sources",
	settings: {
		title: "Settings",
		subtitle: "Local-first. Everything on this page runs on your device.",
		profileTipTitle: "Personalization",
		profileTipBody:
			"Your identity, custom instruction, language, and reader preferences are on your Profile page.",
		engine: "Engine Status",
		version: "Version",
		sourcesCount: "{{on}}/{{total}} on",
		articles: "Articles",
		llm: "LLM",
		mode: "Mode",
		modeIntelligence: "Intelligence",
		modeNews: "News",
		modeIntelligenceHint:
			"Insights, significance, impact, and takeaways are generated by your LLM provider.",
		modeHint:
			"Intelligence mode uses your provider to generate insights. News mode shows the ranked feed without AI enrichment.",
		intelligence: "Intelligence Provider",
		intelligenceHint:
			"Optional. Without a provider, Vorynth stays in news mode.",
		verify: "Verify",
		addProvider: "Add Provider",
		appearance: "Appearance",
		theme: "Theme",
		themeHint: "Light (Precision Minimalism) / Dark (Obsidian Intelligence)",
		themeToggleAria: "Toggle theme",
		switchToLight: "Switch to light",
		switchToDark: "Switch to dark",
		language: "Language",
		languageMovedToProfile:
			"Language settings now live on your Profile page, alongside your identity and personalization.",
		languageHint:
			"Vorynth ships in 10 languages — English, فارسی, العربية, 한국어, 日本語, 中文, עברית, Español, Deutsch, Русский — each laid out with the right direction (RTL for Arabic, Persian, Hebrew, …). Add any other language by exporting the English catalog, translating it, and importing it back.",
		active: "Active",
		import: "Import Catalog",
		export: "Export English",
		remove: "Remove",
		builtIn: "Built-in",
		custom: "Custom",
		languageSearchPlaceholder: "Search languages…",
		languageExportNote:
			"Export gives you vorynth-en.json. Translate every value, keep the keys, save as e.g. fr.json, and import — Vorynth will lay out RTL automatically.",
		importedTranslations: "Imported translations",
		importDialogTitle: "Invalid catalog JSON",
		importDialogBody: "Make sure it's a Vorynth en.json you translated.",
		removeLanguageTitle: "Remove language?",
		removeLanguageBody:
			"This custom translation will be removed. Vorynth will switch back to its bundled translation for that language — or English. Your own files are untouched.",
		ok: "OK",
		close: "Close",
		dataOwnership: "Data Ownership",
		dataHint: "Your data lives in a local SQLite file.",
		exportBackup: "Export Backup",
		restore: "Restore",
		delete: "Delete All Data",
		recollect: "Re-collect all sources",
		recollectHint:
			"Re-fetches every article from every source and updates existing entries in place. Use this when you know articles have changed at their source or you're testing a new collection feature. For a single source, use Sources. Not generally recommended.",
		recollectButton: "Re-collect all",
		recollectConfirm:
			"Are you sure? This will re-fetch every enabled source and update existing articles. Related insights and media are preserved.\n\nThis is only recommended if articles have changed at their source or you're testing a new collection feature.",
		recollectBusy: "Re-collecting…",
		regenerateInsights: "Regenerate All Insights",
		regenerateInsightsHint:
			"Regenerates the AI triad (Why It Matters, Impact, Takeaway) for every story using your current AI Output Language. Existing insights are updated in place.",
		regenerateInsightsButton: "Regenerate All Insights",
		regenerateInsightsConfirm:
			"Are you sure? This will regenerate AI details for all existing stories using your selected output language. Each story will be sent to your LLM provider for re-analysis.\n\nThis may use a significant number of API tokens depending on how many stories are in your database.",
		regenerateInsightsBusy: "Regenerating…",
		translateTitles: "Translate Stories",
		translateTitlesHint:
			"Translates every story's title AND body into your selected AI Output Language — 5 stories per AI request. The originals are preserved and an Original/Translated toggle appears next to titles and next to the body in the reader.",
		translateTitlesButton: "Translate All Stories",
		translateTitlesConfirm:
			"Are you sure? This will translate every story's title and body to your selected output language, 5 stories per AI request. The original titles and bodies are preserved and can be toggled in the reader.\n\nThis may use API tokens depending on how many untranslated stories exist.",
		translateTitlesBusy: "Translating stories…",
		// v1.8.0 — data health check: daily self-healing job.
		dataHealthTitle: "Data health check",
		dataHealthAutoLabel: "Automatic daily check",
		dataHealthAutoHint:
			"Once a day Vorynth quietly repairs your stored stories: it fetches the full text of stories that only have a feed snippet, re-translates (or clears) translations that went stale when an origin was upgraded, and — when Intelligence mode is on — generates the missing AI analysis. It runs as a visible job in the tray. Turn this off to stop the automatic run; the button below still works.",
		dataHealthBusy: "Checking…",
		dataHealthRun: "Run data check now",
		dataHealthConfirm:
			"Run the data health check now? It fetches the full text of snippet-only stories, repairs stale translations, and — when Intelligence mode is on — generates missing AI insights. The LLM parts use API tokens and respect the rate limit; the job shows in the tray and can be canceled.",
		welcome: "Welcome & Setup",
		showWelcome: "Show the welcome screen when Vorynth starts",
		showWelcomeHint:
			"The welcome screen introduces Vorynth and lets you add AI. Turn it off to skip it — you can always open it again from here.",
		openWelcome: "Open the welcome screen",
		welcomeStatusPending: "Not set up yet",
		welcomeStatusDone: "Setup complete",
		welcomeStatusSkipped: "Welcome skipped — open it any time from here",
		// v1.8.0 — source lists: hide 18+ lists from browsing by default.
		sourceListsTitle: "Source lists",
		hideAdultLists: "Hide 18+ lists",
		hideAdultListsHint:
			"Only community SOURCE LISTS flagged 18+ are hidden from the Sources page until you show one. Stories, insights, and search results are never filtered by this — and nothing is ever deleted.",
		// v1.8.0 — the brief summary's ORIGINAL version language.
		summaryLanguageTitle: "Summary original language",
		summaryOriginalLanguage: "Original language",
		summaryOriginalLanguageHint:
			"The Generate Brief summary is written in your AI output language; this picks the language of its ORIGINAL version. Auto uses the majority language of the stories in the summary — or pin one. The translated version always follows your AI output language.",
		mediaTitle: "Media",
		showMediaDownloadWarning: "Show media download warning",
		showMediaDownloadWarningHint:
			"Before the first download, confirm the blog's privacy policy may restrict it. Turn off to skip the warning; turn back on anytime.",
		// v1.8.0 — launch behavior: start at login + background mode.
		launchTitle: "Startup & background",
		launchAtLogin: "Launch at login",
		launchHintMac:
			"Adds Vorynth to Login Items — it starts automatically when you sign in to your Mac.",
		launchHintWindows:
			"Adds Vorynth to Startup apps — it starts automatically when you sign in to Windows.",
		launchHintLinux:
			"Adds Vorynth to Startup Applications — it starts automatically when you sign in.",
		startHiddenLabel: "Start without a window",
		startHiddenHint:
			"Vorynth launches straight to the menu bar — no window pops up. Click the tray icon to open it. Pairs with Launch at login so signing in stays out of the way. Takes effect on the next start.",
		backgroundLabel: "Run in background",
		backgroundHint:
			"Keep Vorynth working after you close the window — it leaves the Dock and stays in the menu bar, keeping on collecting.",
		backgroundTip:
			"When the window is closed, Vorynth keeps running in the background: it leaves the Dock entirely (nothing dead to click) and lives in the menu bar, your sources keep being collected so the brief is ready when you return, and Quit from the tray fully exits.",
		// v1.8.0 — advanced features: reveal the Plugins page (power-user gate).
		advancedTitle: "Advanced",
		showAdvancedFeatures: "Show advanced features",
		showAdvancedFeaturesHint:
			"Reveals the Plugins page — the source connectors and UI plugins Vorynth runs. Most people never need this: connectors for your sources resolve automatically. Turn it on only if you want to see and manage the machinery yourself.",
		searchPlaceholder: "Search settings…",
		searchHint: "Type to filter — sections without a match are dimmed.",
		searchButton: "Search",
		categoryGeneral: "General",
		categoryIntelligence: "Intelligence",
		categoryData: "Data & Health",
		categorySources: "Sources",
		categoryPlugins: "Plugins",
		// v1.8.0 — per-category search keywords, localized per UI language so the
		// Settings search matches the selected language (not just English).
		searchGeneral:
			"engine status version mode news intelligence appearance theme welcome setup onboarding launch startup background login language profile advanced features plug updates update upgrade check notifications bell job os",
		searchIntelligence:
			"provider llm gemini openai anthropic ollama api key usage tokens requests rate limit summary original language regenerate insights translate stories ai",
		searchData:
			"retention delete trash data health check repair ownership backup restore export delete all re-collect collect history recording media download storage usage size space clear stories",
		searchSources: "source lists hide adult 18+",
		searchPlugins: "plugin plugins extensions",
		// Cross-page hint topics — matched in the selected language too.
		searchCrossLanguage: "language languages app language ui language",
		searchCrossAi:
			"ai output output language intelligence language ai language",
		searchCrossIdentity: "identity who you are interests behavior summary",
		searchCrossReading: "reading reader font font size card click",
		searchCrossSettings:
			"updates update theme appearance storage usage notifications mode",
		// v1.8.0 — auto-update (GitHub releases → download → install → restart).
		updatesTitle: "Updates",
		updatesHint:
			"Vorynth checks the official GitHub releases for a newer version and updates itself in the background. Check now, or wait — a new version notifies you automatically.",
		updatesCurrent: "Current version",
		updatesLastChecked: "Last checked",
		updatesNever: "Never",
		updatesCheck: "Check for updates",
		updatesChecking: "Checking…",
		updatesUpToDate: "You're up to date",
		updatesInstall: "Install {{version}}",
		updatesError: "Update check failed:",
		updatesDevHint:
			"Automatic updates are only available in the installed app — this development build can't replace itself.",
		// v1.8.0 — storage & usage (what's on disk + engine resource usage).
		storageTitle: "Storage & Usage",
		storageHint:
			"What Vorynth holds on your disk and what the engine is using right now.",
		storageLoading: "Measuring…",
		storageTotal: "Total data",
		storageApp: "App",
		storageRefresh: "Refresh",
		storageLibraryDatabase: "Database (stories & everything)",
		storageLibraryMedia: "Media library",
		storageLibraryBackups: "Backups",
		storageLibraryPlugins: "Plugins",
		storageItems: "{{count}} items",
		storageStoriesLabel: "{{count}} stories",
		storageStoriesSize: "≈ {{size}} of story text",
		storageClearStories: "Clear all stories",
		storageClearStoriesBody:
			"This permanently deletes all {{count}} stories from your database.",
		storageClearStoriesKept:
			"Bookmarked stories and stories inside collections are always kept.",
		storageClearStoriesRecommend:
			"Not recommended — prefer Auto-delete retention above, so old stories leave automatically while new ones keep arriving.",
		storageClearStoriesConfirmLabel: "Delete all stories",
		storageMediaLabel: "{{count}} media items",
		storageMediaSize: "{{size}} kept locally",
		storageClearMedia: "Clear media",
		storageClearMediaBody:
			"This permanently removes {{count}} locally-kept media items ({{size}}) from disk.",
		storageClearMediaHint:
			"Media stays available on the source pages — Vorynth streams it from there again. Keep anything you need before clearing.",
		storageClearMediaConfirmLabel: "Delete media",
		storageClearing: "Clearing…",
		storageMeasured: "Measured at {{at}}",
		storageSystemTitle: "System usage",
		storageRam: "RAM in use",
		storageHeap: "Heap",
		storageCpu: "CPU",
		storageUptime: "Uptime",
		storageSystemMemory: "Free / total memory",
		// v1.8.0 — custom themes: import / export / edit / delete + AI flow.
		themeImport: "Import theme",
		themeCustomizeAi: "Customize with AI",
		themeExportCurrent: "Export current theme",
		themeExport: "Export",
		themeEdit: "Edit",
		themeDelete: "Delete",
		themeCustomThemes: "Custom themes",
		themeImportDialogTitle: "Import theme",
		themeImportBody:
			"Paste the theme JSON, or pick a .json file. Imported themes are stored on this device and can be edited, exported, or deleted anytime.",
		themePastePlaceholder:
			'{"id":"aurora", "name":"Aurora", "light":{...}, "dark":{...}}',
		themePickFile: "Choose file",
		themeImportAction: "Import",
		themeErrorInvalidJson: "The file isn't valid JSON.",
		themeErrorNotObject: "The theme must be a JSON object.",
		themeErrorBadId: '"id" must be a lowercase slug (letters, digits, dashes).',
		themeErrorReservedId: '"id" cannot be "light" or "dark".',
		themeErrorBadName: '"name" is required.',
		themeErrorNoTokens: "The theme has no --color-* tokens.",
		themeErrorBadTokens: '"light" and "dark" must be objects.',
		themeErrorBadTokenValue: "Every token value must be a string.",
		themeErrorBadTriplet:
			'Every --color-* value must be an "r g b" triplet (e.g. "255 87 51").',
		themeErrorBadIcon: '"icon" must be a string.',
		themeErrorBadBackground:
			'"background" must be an object with optional "light"/"dark" strings.',
		themeAiDialogTitle: "Customize with AI",
		themeAiBody:
			"Copy the prompt, paste the theme JSON into it, and send it to ChatGPT or any LLM. It replies with a new theme JSON — paste that back through Import.",
		themeAiPromptLabel: "Prompt",
		themeAiJsonLabel: "Your theme JSON",
		themeAiCopy: "Copy prompt",
		themeAiCopied: "Copied!",
		themeEditDialogTitle: "Edit theme",
		themeEditBody:
			"Edit the JSON and save — the theme updates everywhere it's used.",
		themeEditSave: "Save",
		themeDeleteConfirm:
			"Delete this custom theme? It can't be recovered (export it first if you want a copy).",
		// v1.8.0 — notification center + OS notifications.
		notificationsTitle: "Notifications",
		notificationsHint:
			"What the bell in the top bar reports. Optionally mirror events to your system's notification center.",
		notificationsEnabled: "Enable notifications",
		notificationsEnabledHint:
			"Show notifications in the top-bar bell when a job finishes or a new version is available.",
		notificationsOs: "System notifications",
		notificationsOsHint:
			"Also post to your operating system's notification center. macOS asks for permission the first time.",
		notificationsJobFinished: "Job finished",
		notificationsJobFinishedHint:
			"A bell (and system) notification when a background job completes or fails — collect, generate, translate, and more.",
		notificationsUpdateAvailable: "New version available",
		notificationsUpdateAvailableHint:
			"A bell (and system) notification when a newer Vorynth is available.",
		// v1.8.0 — cross-page search hint (settings ↔ profile).
		crossPageHint: "Found on the {{page}} page — {{section}}",
		crossPageGo: "Go to {{page}}",
		// v1.8.0 — font customization (Settings → Appearance).
		fontFamily: "Font",
		fontDefault: "Default (Geist)",
		fontSize: "Text size",
		fontSearch: "Search fonts…",
		fontImport: "Import custom font",
		fontReset: "Reset",
		fontImportFailed: "Couldn't load that font file.",
	},
	provider: {
		label: "Label",
		model: "Model",
		apiKey: "API Key",
		baseUrl: "Base URL",
		cancel: "Cancel",
		save: "Save Provider",
		saving: "Saving…",
		active: "Active",
		setActive: "Set active",
		switchToIntelligence: "Switch to Intelligence mode",
		switchToNews: "Switch to News mode",
		keyStored: "key stored",
		noKey: "no key",
		keyUndecryptable: "key can't be decrypted",
		undecryptableHint:
			"This key can't be decrypted — the local encryption key was likely lost when your data was restored or cleaned up. Remove this provider and add it again with your API key.",
		labelPlaceholder: "My Gemini key",
		apiKeyPlaceholder: "paste key…",
		baseUrlPlaceholder: "http://localhost:11434/v1",
		removeAria: "Remove",
	},
	onboarding: {
		welcome: "Welcome to Vorynth",
		welcomeBody:
			"Vorynth is a local-first personal intelligence engine for the tech world — software engineering, security, AI, cloud. It collects the flood from your trusted sources, ranks it into one short daily brief, and explains each story with AI context: why it matters, what it affects, and what to do about it. Everything stays on this device — no account, nothing shared.",
		privacy: "Private by design",
		privacyBody:
			"Your sources, stories, and reading history stay on this device. No account, no tracking, nothing shared.",
		begin: "Get Started",
		config: "Make it smarter (optional)",
		configBody:
			"Connect an AI service to add “Why it matters”, “Impact”, and a recommended next step to every story. Skip this — Vorynth works great on its own.",
		selectProvider: "Choose an AI service",
		apiKey: "API Key",
		apiKeyHint:
			"Stored encrypted on this device and sent only to the service you chose.",
		newsOnly: "Skip for now — News mode",
		newsOnlyBody:
			"News mode collects and ranks stories without AI. You can add an AI service any time in Settings.",
		// v1.8.0 — explain the modes and why a key is asked BEFORE the provider grid.
		modesTitle: "News mode vs. Intelligence mode",
		newsModeBody:
			"News mode collects and ranks stories with no AI — no key needed, fully private, works on any machine.",
		intelModeBody:
			"Intelligence mode adds AI context to every story — why it matters, its impact, and a takeaway. It needs one of the providers below.",
		whyKeyTitle: "Why do we ask for a key?",
		whyKeyBody:
			"Your stories never leave this device. The key is stored encrypted and your data goes only to the provider you pick — for the analysis.",
		localTitle: "Privacy first? Run it locally.",
		localBody:
			"If you have good hardware, we recommend a strong local model — DeepSeek or another good open model — through Ollama. Nothing leaves your machine.",
		cloudTitle: "Speed first?",
		cloudBody:
			"Gemini, OpenAI, or Claude are the recommended choices when speed matters and you're comfortable with a cloud provider.",
		futureProvidersTip:
			"Tip: more providers will be added to this list over time — check the changelog for what's new.",
		continue: "Continue",
		back: "Back",
		savingProvider: "Saving…",
		topics: "What matters to you?",
		topicsBody:
			"Pick a few areas so your brief surfaces the stories you care about.",
		topicsHint:
			"These shape your brief's emphasis — change them anytime in Profile.",
		ready: "You're all set",
		readyBody:
			"Vorynth is about to pull the latest stories from your sources. This takes a moment.",
		initialize: "Start my first brief",
		initializing: "Preparing…",
		systemReady: "Your data never leaves this device.",
		skip: "Skip setup",
		skipHint:
			"Skip the setup and start with default settings — you can open the welcome screen again from Settings.",
		ollamaLocal: "Ollama (local)",
		apiKeyPlaceholder: "sk-...",
		// v1.8.0 — language picks on the first step + the empty-topics tip + recap.
		appLanguage: "Application language",
		aiLanguage: "AI output language",
		languageSearch: "Search languages…",
		emptyTopicsBody:
			"No topics selected — Vorynth's official sources will be enabled by default so your brief isn't empty. Keep them?",
		emptyTopicsKeep: "Keep official sources",
		emptyTopicsDisable: "Disable them",
		// v1.8.0 — explicit official-sources default on the topics step.
		officialSources: "Keep official sources enabled",
		officialSourcesHint:
			"Vorynth's official developer-news list fills your brief by default. Turn it off if you only want your own topics.",
		emptyTopicsOffBody:
			"No topics selected and official sources are off — your brief will be empty. Keep official sources on?",
		recapMode: "Mode",
		recapIntelligence: "Intelligence",
		recapNews: "News",
		recapTopics: "Topics",
		recapNoTopics: "None — official sources",
		recapUiLanguage: "App language",
		recapAiLanguage: "AI language",
		recapNote: "Everything can be changed anytime in Settings and Profile.",
	},
	analyzing: {
		title: "Distilling Intelligence",
		body: "The local engine is processing your sources. This takes a moment.",
		collecting: "Collecting sources",
		normalizing: "Normalizing content",
		dedup: "Detecting duplicates",
		classifying: "Classifying topics",
		ranking: "Ranking importance",
		analyzing: "Analyzing impact",
		localizing: "Localizing output",
		report: "Compiling brief",
		running: "Running…",
		done: "Done",
		starting: "Starting the engine…",
		generationFailed: "Generation failed.",
	},
	tiers: {
		signal: "Signal",
		trend: "Trend",
		"low-noise": "Low Noise",
	},
	common: {
		collect: "Collect",
		collecting: "Collecting…",
		generate: "Generate Brief",
		generating: "Generating…",
		back: "Back",
		cancel: "Cancel",
		noResults: "No matches",
	},
	search: {
		title: "Search",
		subtitle:
			"Search across everything Vorynth has collected. Keyword is always available; Ask AI uses RAG over your stories.",
		placeholder: "Search stories…",
		search: "Search",
		searching: "Searching…",
		newsModeHint: "News mode — add an LLM provider to use Ask AI",
		modeKeyword: "Keyword",
		modeAskAi: "Ask AI",
		advanced: "Advanced search",
		hideAdvanced: "Hide advanced search",
		askingBackground:
			"Asking AI in the background — you can navigate away; the answer appears here when it's ready (rate-limited at 5 req/min).",
		answer: "Answer",
		citedCount: "{{count}} cited",
		tokensUsed: "{{count}} tokens",
		openCitation: "Open: {{title}}",
		moreCitations: "+{{count}} more",
		showLess: "Show less",
		expandInline: "Expand inline",
		export: "Export",
		viewFullResult: "View full result",
		savingToHistory: "Saving to history…",
		fullResultUnavailable: "Full result unavailable",
		saving: "Saving…",
		exportSourcesHeader: "Sources",
		matches_one: "{{count}} match",
		matches_other: "{{count}} matches",
		showingOf: "showing {{shown}} of {{total}}",
		viewAllResults: "View all {{count}} results",
		score: "score {{value}}",
		readSource: "Read source",
		advancedHint:
			"Structured filters over the collected corpus — for research-grade queries.",
		keywords: "Keywords",
		fullTextTermsPlaceholder: "Full-text terms (optional)",
		author: "Author",
		authorPlaceholder: "e.g. BrianKrebs",
		source: "Source",
		filterBySourceAria: "Filter by source",
		allSources: "All sources",
		collectedFrom: "Collected from",
		to: "to",
		domains: "Domains",
		hasAiAnalysis: "Has AI analysis",
		searchWithFilters: "Search with filters",
		clearFilters: "Clear filters",
		emptyTitleAi: "Ask anything",
		emptyTitleKeyword: "Find stories",
		emptyAiEnabled:
			"Ask a question in natural language — Vorynth answers from your collected stories, with citations.",
		emptyAiNeedsProvider:
			"Ask AI needs an LLM provider. Add one in Settings, or switch to Keyword for instant results.",
		emptyKeyword:
			"Keyword search runs instantly over every title and body Vorynth has collected. Press Enter or hit Search.",
	},
	categories: {
		ai: "AI",
		"software-engineering": "Software Engineering",
		"programming-languages": "Programming Languages",
		"web-development": "Web Development",
		backend: "Backend",
		devops: "DevOps",
		cloud: "Cloud",
		security: "Security",
		"open-source": "Open Source",
		other: "Other",
	},
	// v1.8.0 — permanent delete of archived items (archive page).
	archive: {
		deleteTitle: "Delete permanently?",
		deleteMessage:
			"This removes the item for good — its note, tags, and any bookmark go with it. This can't be undone.",
		deleteConfirm: "Delete",
		title: "Archive",
		subtitle:
			"Everything Vorynth has collected — stories, saved items, summaries, searches, and AI answers — in one searchable space.",
		filterPlaceholder: "Filter by title or note…",
		filterAria: "Filter items",
		filterAll: "All",
		editNoteAria: "Edit note",
		unarchiveAria: "Unarchive",
		archiveAria: "Archive",
		deletePermanentlyAria: "Delete permanently",
		notePlaceholder: "Write a note…",
		moveToCollectionAria: "Move to collection",
		uncategorize: "Uncategorize",
		moveTo: "Move to…",
		archived: "Archived",
		item_one: "item",
		item_other: "items",
		showArchived: "Show archived",
		showingArchived: "Showing archived",
		itemsTitle: "Items",
	},
	// v1.1.0 — native article reader + media control.
	article: {
		loading: "Loading…",
		notFound: "Article not found",
		back: "Back",
		backToBrief: "Back to Brief",
		by: "by",
		unknownSource: "Unknown source",
		readOriginal: "Read original article",
		/** Insight page → article reader bridge (v1.8.0). */
		readFullArticle: "Read the full article",
		insightExplainer:
			"This is the AI insight — the analysis and what to do about it. For the whole story, open the article reader.",
		openArticleReader: "Open article reader",
		noContent: "No body text was stored for this article.",
		/** Translation toggles (title + body) in the reader and Brief. */
		translated: "Translated",
		showOriginalTitle: "Show original title",
		showTranslatedTitle: "Show translated title",
		showOriginalBody: "Show original body",
		showTranslatedBody: "Show translated body",
		media: "Media",
		mediaFromSource: "streamed from source",
		releaseAll: "Release all",
		fromSource: "remote · from source",
		keptLocal: "kept locally",
		keepLocal: "Keep locally",
		releaseLocal: "Release local copy",
		zoom: "Zoom",
		close: "Close",
		markRead: "Mark read",
		read: "Read",
		save: "Save",
		saved: "Saved",
		share: "Share",
		original: "Original",
		/** Per-story translate + export (v1.8.0). */
		translate: "Translate",
		translating: "Translating…",
		translateHint:
			"Translate this story's title and text into your intelligence language.",
		translateFailed:
			"Translation failed — check your LLM provider and try again.",
		/** Transparency (v1.8.0) — why a story has no AI insight on the Brief. */
		noInsightNews:
			"Why It Matters / Impact / Takeaway appear when an LLM provider is configured — Vorynth is in News mode.",
		noInsightPending: "AI analysis hasn't run for this story yet.",
		/** Per-story insight Generate pill (v1.8.0). */
		generateInsight: "Generate",
		generateInsightBusy: "Generating…",
		generateInsightHint:
			"Generate this story's AI analysis (Why It Matters / Impact / Takeaway).",
		generateInsightFailed: "Couldn't generate the analysis — try again.",
		noInsightNoContent:
			"Can't analyze this story — it has no body text. Re-collect the source to fetch the full article first.",
		/** Per-story Re-collect button (v1.8.0) — reader footer + brief card. */
		recollect: "Re-collect",
		recollecting: "Re-collecting…",
		recollectHint:
			"Re-fetch this story's original article, refresh its full text, re-translate if needed, and generate its AI analysis.",
		recollectFailed: "Re-collect failed — check the connection and try again.",
		/** Per-story Re-translate pill (v1.8.0) — every translated story. */
		retranslate: "Re-translate",
		retranslating: "Re-translating…",
		retranslateHint:
			"Run a fresh translation with new AI output — useful after changing your language, or when the current translation looks off.",
		retranslateFailed: "Re-translation failed — try again.",
		/** Footer overflow menu (v1.8.0) — Translate/Re-translate, Re-collect, and
		 *  the Article/Insights card view all live behind More. */
		more: "More",
		moreAria: "More story actions",
		viewArticle: "Article view",
		viewInsights: "Insights view",
		viewArticleHint:
			"Show this story's article post instead of the AI insights.",
		viewInsightsHint:
			"Show this story's AI insights (Why It Matters / Impact / Takeaway) instead of the raw article.",
		/** Transparency (v1.8.0) — stored body carries extraction junk. */
		contentCorruptedNote:
			"This story's text looks like it was captured from the page's interface, not the article itself. Re-collect to fetch the original from the source.",
		export: "Export",
		exportTitle: "Export this story",
	},
	// v1.8.0 — the shared Export dialog (any content: article, insight, answer,
	// history entry, period brief). Neutral title — not "story"-specific.
	export: {
		exportTitle: "Export",
		closeAria: "Close export dialog",
	},
	reader: {
		supportTitle: "Support the author",
		supportBody:
			"This story's canonical home is the site that published it — that's where the author gets credit and views. Consider opening the original. You can still read it here if you prefer.",
		article: "Article",
		openOriginal: "Open original",
		readInVorynth: "Read in Vorynth",
		dontShowAgain: "Don't show this again —",
		changeInProfile: "change it later in Profile.",
	},
	profile: {
		title: "Profile",
		subtitle:
			"How Vorynth knows you. Your identity, custom instruction, and reading behavior — all local.",
		settingsTipTitle: "App settings",
		settingsTipBody:
			"Engine status, LLM provider, theme, and data management live on the Settings page.",
		loading: "Loading profile…",
		localUser: "Local User",
		localEngine: "Local Engine",
		identity: "Identity",
		firstName: "First name",
		firstNamePlaceholder: "Given name",
		lastName: "Last name",
		lastNamePlaceholder: "Family name",
		alias: "Alias",
		aliasPlaceholder: "A handle you prefer to go by",
		saveIdentity: "Save identity",
		// v1.9.0 — education & experience (collected for future source/category/tag
		// suggestions; everything stays accessible).
		educationTitle: "Education & experience",
		fieldOfStudy: "Field of study",
		fieldOfStudyPlaceholder: "e.g. Computer Science",
		degreeLevel: "Degree",
		degreeNone: "Not set",
		degree: {
			"high-school": "High school",
			associate: "Associate",
			bachelor: "Bachelor's",
			master: "Master's",
			phd: "PhD",
			other: "Other",
		},
		experienceLevel: "Experience",
		experienceNone: "Not set",
		experience: {
			beginner: "Beginner",
			intermediate: "Intermediate",
			advanced: "Advanced",
			expert: "Expert",
		},
		educationTip:
			"Vorynth will soon suggest sources, categories, and tags matched to your field and degree — everything else stays accessible.",
		saving: "Saving…",
		saved: "Saved",
		saveFailed: "Save failed. Check the engine is running and try again.",
		customInstruction: "Custom instruction",
		customInstructionHint:
			"A directive that biases how Vorynth's AI responds to you — tone, depth, language, what to emphasize or avoid. Applied to Ask-AI search and generate operations.",
		customInstructionPlaceholder:
			"e.g. Be concise and technical. Prefer examples over theory. Avoid marketing language.",
		improve: "Improve",
		improving: "Improving…",
		improvedPreview: "Improved preview",
		restoreOriginal: "Restore your draft",
		apply: "Apply",
		discard: "Discard",
		save: "Save",
		needProvider:
			"Add an LLM provider in Settings to use AI-assisted features.",
		improveFailed: "Couldn't improve the instruction. Try again.",
		behaviorSummary: "Behavior summary",
		generate: "Generate",
		regenerate: "Regenerate",
		generating: "Generating…",
		generateFailed: "Couldn't generate the summary. Try again.",
		generatedAt: "Generated",
		noSummary:
			"No summary yet. Generate one from your search and briefing history — it describes what you tend to read and search for.",
		interests: "Interests & topics",
		interestsHint:
			"Derived from your history — the categories and queries that show up most across your briefings and searches.",
		topCategories: "Top categories",
		recentSearches: "Recent searches",
		noActivity:
			"No activity yet. Run a search or read a briefing to populate this.",
		readerSettings: "Reader settings",
		supportReminder: "Show 'support the author' reminder",
		supportReminderHint:
			"Nudges you toward the original site before opening the in-app reader.",
		keepMediaLocal: "Keep media locally by default",
		keepMediaLocalHint:
			"When on, media from articles you open is downloaded for offline reading. Off by default — media streams from the source.",
		aiLanguage: "AI Output Language",
		aiLanguageHint:
			"The language Vorynth's AI uses when answering your questions, generating briefs, and writing summaries. Choose the language you want insights in.",
		/** Reader action bar customization (v1.8.0). */
		readerActions: "Reader actions",
		readerActionsHint:
			"Choose which story actions stay in the reader's bottom bar. Everything else moves behind the 'More ⋮' menu — nothing is hidden.",
		pinned: "In the reader bar",
		moreMenu: "Behind 'More ⋮'",
		readerActionsOverflow:
			"The reader bar is designed for five actions — pinning more can crowd it.",
		/** Story-card click behavior (v1.8.0). */
		cardClick: "Card click",
		cardClickHint: "How a story card reacts when you press and drag across it.",
		dragSelectsText: "Drag selects text",
		dragSelectsTextHint:
			"When on (default), dragging the mouse over a story selects the text without opening it — a clean click is required to open. Turn off if you never select text with the mouse and want any press-release to open the story.",
		aiLanguageAria: "AI output language",
		resetAll: "Reset all",
		resetting: "Resetting…",
		categoryIdentity: "Who you are",
		categoryAi: "How the AI writes",
		categoryLanguages: "Languages",
		categoryReading: "Reading",
		// v1.8.0 — per-category search keywords, localized per UI language so the
		// Profile search matches the selected language (not just English).
		searchIdentity:
			"identity name first last alias behavior summary interests topics education degree field of study experience",
		searchAi: "custom instruction ai output language write",
		searchLanguages:
			"language ui english persian arabic korean japanese chinese hebrew spanish german russian",
		searchReading:
			"reader settings support author reminder media local actions card click drag selects text",
	},
	media: {
		title: "Local media",
		subtitle:
			"Article media you've chosen to keep on this device. Nothing is stored without your explicit opt-in — release anything here, or purge it all.",
		back: "Back",
		loading: "Loading…",
		totalSize: "Total size",
		articles: "Articles",
		items: "Items",
		itemsUnit: "items",
		empty: "Nothing kept locally",
		emptyBody:
			"Open any article and tap the keep icon on a media item to store it here for offline reading.",
		release: "Release",
		purgeAll: "Purge all",
		purgeConfirm:
			"Delete every locally-kept media file? Articles themselves are not affected.",
		unknownSource: "Unknown source",
		/** Per-item download (v1.8.0). */
		download: "Download",
		downloadAria: "Download {{caption}}",
		image: "Image",
		video: "Video",
		downloadWithAttribution: "Download with attribution",
		downloadWithAttributionHint:
			"Credit the blog, article title, and source URL in the image itself.",
		downloadOriginal: "Download original",
		downloadOriginalHint: "The file exactly as it was stored, no credit added.",
		videoDownloadsAsIs:
			"Credit can only be drawn into images — videos download as the original file.",
		viaVorynth: "Downloaded via Vorynth",
		downloadFailed: "The download failed — try again.",
		downloadDisclaimerTitle: "Check this blog's policy",
		downloadDisclaimerBody:
			"This blog's privacy policy may restrict downloading its content. Vorynth lets you save it anyway — you're responsible for how you use what you download. You can turn this warning back on anytime in Settings → Media.",
		/** Preview (v1.8.0) — click a thumbnail to view it full size. */
		previewAria: "Preview {{caption}}",
		close: "Close",
	},
	plugins: {
		title: "Plugins",
		subtitle:
			"The adapters Vorynth uses to collect sources — and the UI plugins that add their own docs, settings, menu entries, and themes. Every plugin can be switched off except the Icon Pack, which powers the app's own icons and fonts and is always on. Turning off an adapter pauses its sources, and they come back exactly as they were when you switch it on again.",
		back: "Back",
		loading: "Loading plugins…",
		core: "Core",
		coreHint:
			"Core — ships with Vorynth. Switching it off pauses its sources; each source keeps its own state, so they resume exactly as they were when you turn it back on.",
		official: "Official",
		officialHint:
			"An official connector — built and live-tested by Vorynth against a real reference source.",
		sectionOfficial: "Official connectors",
		ui: "UI",
		uiHint: "Adds docs, settings, menu entries, and themes to the app.",
		alwaysOn: "Always on",
		alwaysOnHint:
			"Vorynth needs this plugin — it powers the app's own icons and fonts, so it can't be switched off.",
		badgeTheme: "Theme",
		badgeThemeHint: "Ships a theme — pick it in Settings → Appearance.",
		badgeIcons: "Icons",
		badgeIconsHint: "Ships offline icon sets other plugins can use.",
		badgeFonts: "Fonts",
		badgeFontsHint: "Ships offline fonts other plugins can use.",
		badgeRenderer: "Story Renderer",
		badgeRendererHint:
			"Exports stories as Markdown, themed HTML, or a screenshot.",
		badgeCopyright: "Copyright",
		badgeCopyrightHint: "Adds copyright attribution to media downloads.",
		on: "On",
		off: "Off",
		disabledDependency: "A dependency is off — this plugin is paused.",
		enabled: "Enabled",
		disabled: "Disabled",
		active: "In use",
		activeHint:
			"At least one enabled source collects through this connector right now.",
		idle: "Idle",
		idleHint:
			"No enabled source currently uses this connector — it's ready but not collecting.",
		toggleError: "Couldn't change the plugin. Try again.",
		dependencies: "Depends on",
		version: "v{{version}}",
		empty: "No plugins",
		docs: "How plugins work",
		settingsSectionTitle: "{{name}} settings",
		disabledTitle: "Plugin {{id}} is off",
		disabledBody:
			"Enable it on the Plugins page to see its page and contributions.",
		notLoadedTitle: "Plugin {{id}} isn't loaded",
		notLoadedBody:
			"The plugin bundle wasn't found or failed to load. It ships with the app — reinstall or update to restore it.",
		readDocs: "Read the guide",
		noView:
			"This plugin has no standalone page — its contributions live in Settings and Docs.",
		installed: "Installed",
		installedHint: "Added from your data/plugins folder — removable.",
		searchPlaceholder: "Search plugins…",
		searchLabel: "Search plugins",
		noSearchResults: "No plugins match “{{q}}”.",
		sectionCore: "Core",
		sectionInstalled: "Installed",
		sectionBuiltIn: "Built-in",
		showCore: "Show core plugins",
		hideCore: "Hide core plugins",
		showCoreHint:
			"Core plugins ship with Vorynth. Hiding them keeps the list focused on what you added.",
		coreHidden: "Core plugins are hidden — {{count}} shown.",
		scan: "Scan for plugins",
		scanHint:
			"Look for plugin folders dropped into the data/plugins directory.",
		scanning: "Scanning…",
		scanResultAdded: "{{count}} plugin(s) installed",
		scanResultRemoved: "{{count}} plugin(s) removed",
		scanError: "Couldn't scan for plugins. Try again.",
		// v1.8.0 — official connector registry from GitHub.
		checkConnectors: "Check GitHub for connectors",
		checkConnectorsHint:
			"Fetches the official connector registry from the Vorynth GitHub repo — provisions official connectors (like arXiv) so they resolve like built-ins.",
		connectorsChecking: "Checking…",
		connectorsAdded: "{{count}} official connector(s) provisioned",
		connectorsUpdated: "{{count}} connector(s) updated",
		connectorsSkipped: "{{count}} connector(s) skipped (needs a newer Vorynth)",
		connectorsUpToDate: "Official connectors are up to date.",
		connectorsError: "Couldn't reach the connector registry. Try again.",
		install: "Install plugin",
		installHint:
			"Pick a .vorynth-plugin file (a package with the plugin's code and manifest) — no folder digging needed.",
		installing: "Installing…",
		installResult: "{{name}} v{{version}} installed",
		installError:
			"Couldn't install that plugin. The file may be damaged, or its id may belong to a built-in plugin.",
		pluginsDirLabel: "Plugins folder",
		openFolder: "Open folder",
		openFolderHint:
			"Reveals the plugins folder in your file manager (Finder, File Explorer, or your Linux file manager).",
		openInTerminal: "Open in terminal",
		openTerminalHint:
			"Opens the plugins folder in a terminal with that folder as the working directory (PowerShell, Terminal.app, or your Linux terminal).",
		openFolderError: "Couldn't open the folder. Try again.",
		openTerminalError: "Couldn't open the terminal. Try again.",
		desktopOnly: "Only available in the Vorynth desktop app.",
		remove: "Remove",
		removeTitle: "Remove {{name}}?",
		removeBody:
			"Removes this plugin and its bundle from Vorynth. Your data isn't affected.",
		removing: "Removing…",
		removeError: "Couldn't remove the plugin. Try again.",
		// ── Security scan (v1.8.0) ────────────────────────────────────────────
		securityHigh: "Security warning",
		securityMedium: "Security review",
		securityBadgeHint:
			"This plugin's code was flagged by the automatic security scan. Click for details.",
		securityDetailsTitle: "What the scan found",
		securityDetailsHint:
			"The scan only reports patterns — it never executes code. Enable it only if you trust this plugin.",
		securityRepeated: "×{{count}}",
		severityHigh: "High",
		severityMedium: "Medium",
		severityLow: "Low",
		enableRiskyTitle: "Enable {{name}}?",
		enableRiskyBody:
			"The security scan flagged this plugin's code. Enabling it runs that code inside Vorynth — only continue if you trust this plugin.",
		enableAnyway: "Enable anyway",
	},
	sources: {
		back: "Back",
		test: "Test",
		testing: "Testing…",
		testOk: "Works — {{count}} item(s) found",
		testFail: "Couldn't fetch — {{message}}",
		configLabel: "{{label}}",
		testHint:
			"Fetches a few items without saving, so you can check your configuration.",
		// v1.8.0 — source editing + search on the Sources page.
		addSource: "Add Source",
		editSource: "Edit source",
		saveChanges: "Save changes",
		saving: "Saving…",
		adding: "Adding…",
		searchPlaceholder: "Search sources…",
		searchAria: "Search sources by name, URL, or category",
		editAria: "Edit {{name}}",
		nameLabel: "Name",
		namePlaceholder: "OpenAI Blog",
		editTitle: "Edit source",
		addTitle: "Add new source",
		editSubtitle: "A feed Vorynth collects stories from.",
		cancel: "Cancel",
		enableAria: "Enable {{name}}",
		disableAria: "Disable {{name}}",
		deleteAria: "Delete {{name}}",
		// v1.8.0 — group by category/country/city/language.
		groupByAria: "Group sources by",
		groupList: "List",
		groupCategory: "Category",
		groupCountry: "Country",
		groupCity: "City",
		groupLanguage: "Language",
		groupUntagged: "Untagged",
		groupedBy: "All sources by {{dimension}}",
		groupHint:
			"Each group has a master switch — turn a whole category, country, city, or language on or off at once, or flip individual sources. Every source shows its language badge (EN, ES, …).",
		groupEmpty: "No sources in this view.",
		groupSourceCount: "{{count}} sources",
		groupToggleOn: "Enable all {{label}} sources",
		groupToggleOff: "Disable all {{label}} sources",
		// v1.8.0 — geography/language tags on the source form.
		countryLabel: "Country",
		countryHint: "Where is this source based?",
		countryPlaceholder: "Any country",
		cityLabel: "City / region",
		cityHint: "Optional — groups sources by region in the Country view.",
		cityPlaceholder: "e.g. Berlin",
		languageLabel: "Language",
		languageHint: "What language is it published in?",
		languagePlaceholder: "Any language",
		// v1.8.0 — semantic metadata (the "source intelligence layer" data).
		scopeLabel: "Scope",
		scopeHint:
			"How broadly does this source matter? Global affects everyone (Cloudflare), Local is city-level.",
		scopePlaceholder: "Not classified",
		authorityLabel: "Authority",
		authorityHint:
			"How credible is it? Official = the organization itself, Research = papers, Media = journalism, Community = forums, Personal = an individual's blog.",
		authorityPlaceholder: "Not classified",
		impactAreasLabel: "Impact areas",
		impactAreasHint:
			"The domains this source covers — e.g. ai, security, cloud. Structured metadata the intelligence engine reasons over later. Tap a suggestion to add.",
		impactAreasPlaceholder: "e.g. ai, security, cloud",
		deleteTitle: "Delete source?",
		deleteMessage:
			'The source <0>"{{name}}"</0> and all its collected stories will be permanently removed. This cannot be undone.',
		deleteMessageNoName:
			"This source and all its collected stories will be permanently removed. This cannot be undone.",
		deleteConfirm: "Delete source",
		deleteTooltip: "Delete this source",
		disableTooltip: "Disable this source",
		enableTooltip: "Enable this source",
		timeRangeAria: "Time range for {{name}}",
		timeRangeDaysAria: "Time range in days for {{name}}",
		fromDateAria: "From date for {{name}}",
		toDateAria: "To date for {{name}}",
		categoryAria: "Source category",
		categoryLabel: "Category",
		categoryHint:
			"What kind of source is this? Used for ranking and filtering.",
		countryAria: "Source country",
		languageAria: "Source language",
		scopeAria: "Source scope",
		authorityAria: "Source authority",
		customCategoryPlaceholder: "e.g. hardware, robotics, quantum",
		// v1.9.0 — free-form tags with live suggestions.
		tags: "Tags",
		tagsHint:
			"Your own labels to organize and find a source — e.g. work, must-read. Type to search; Enter or + to add. (Impact areas, below, are the domains the source covers; tags are your labels for it.)",
		tagsPlaceholder: "cloud, ai, …",
		tagsAria: "Tags",
		tagsAdd: "Add tag",
		categorySearchPlaceholder: "Search categories…",
		daysPlaceholder: "e.g. 45",
		// v1.8.0 — my-sources.json export/import (share lists across devices).
		exportList: "Export as list",
		exportSelected: "Export {{count}} sources",
		selectedCount: "{{count}} selected",
		selectSourceAria: "Select {{name}}",
		exportDialogTitle: "Export my sources",
		exportDialogBody:
			"{{count}} sources will be exported as my-sources.json — the same format as Vorynth's community source lists, so anyone (or any device) can import it, and you can share it or add it to the repo.",
		exportName: "List name",
		exportNamePlaceholder: "e.g. My favourite blogs",
		exportDescription: "Description",
		exportDescriptionPlaceholder: "What does this list cover?",
		exportCurator: "Curator (optional)",
		exportCuratorPlaceholder: "e.g. your GitHub username",
		exportNsfw: "This list may contain 18+ content",
		exportPublishHint:
			"Tip: drop the file at sources/<curator>/<name>.json in the Vorynth GitHub repo and it becomes a community list others can browse.",
		exportDownload: "Download my-sources.json",
		importList: "Import list",
		importInvalidJson: "That file isn't a valid source list (bad JSON).",
		importInvalid:
			"That file isn't a valid source list — every source needs a name, url, type, and a known adapter.",
		importFailed: "Couldn't import the source list. Try again.",
	},
	// v1.8.0 — curated source lists (official + community).
	sourceLists: {
		enabledTitle: "Source lists",
		enabledSubtitle:
			"Curated groups of sources. Turning a list off hides its sources — nothing is deleted.",
		mySources: "My sources",
		mySourcesHint:
			"Sources you created yourself. They aren't part of any list.",
		browseTitle: "Browse community lists",
		browseHint:
			"Lists contributed through the Vorynth GitHub repo. A list is downloaded once and keeps working offline.",
		checkGithub: "Check GitHub for lists",
		checkingGithub: "Checking…",
		checkFail:
			"Couldn't reach the community catalog. Your saved lists are unchanged.",
		official: "Official",
		community: "Community",
		adultBadge: "18+",
		adultConfirmTitle: "Adult content",
		adultConfirmBody:
			"{{name}} is marked 18+ and may contain content unsuitable for minors. Add it anyway?",
		addList: "Add list",
		addListAria: "Add list {{name}}",
		removeList: "Remove list",
		hideList: "Hide",
		removeConfirmTitle: "Remove this list?",
		removeConfirmBody:
			"{{name}} will be hidden from this page. Nothing is deleted — your sources and every setting you changed are kept, and you can add the list back any time.",
		showAdult: "Show 18+ lists",
		hideAdult: "Hide 18+ lists",
		sourceCount: "{{count}} sources",
		onOfTotal: "{{on}} of {{total}} on",
		offline: "Downloaded — works offline",
		curatorBy: "by {{curator}}",
		noLists: "No community lists yet.",
		noListsHint:
			"Community lists are shared through the Vorynth GitHub repository. Check now to fetch the latest ones.",
		refreshAdded: "Added {{added}}",
		refreshUpdated: "Updated {{updated}}",
		refreshUnchanged: "Unchanged {{unchanged}}",
		refreshRemoved: "Left the repo: {{removed}}",
		refreshSkipped: "Skipped {{skipped}}",
		listToggleAria: "Turn {{name}} off",
		listEnableAria: "Turn {{name}} on",
		expandAria: "Show sources in {{name}}",
		collapseAria: "Hide sources in {{name}}",
		editDisabledNote:
			"Sources in a list can't be deleted individually — hide the whole list instead.",
		sourceCountLabel: "{{count}} sources",
	},
	// Reference Plugin (v1.8.0) — the runtime-plugin template.
	reference: {
		greeting: "Hello — this plugin is alive and contributing.",
		greetingOff: "The greeting is switched off in this plugin's settings.",
		intro:
			"Reference Plugin v{{version}} — a working example of every contribution a runtime plugin can make: theme, settings, docs, and a sidebar entry.",
		contributions: "Contributions",
		theme: "Solar Flare theme in Settings → Appearance",
		settings: "Persisted settings section (two toggles)",
		docs: "Its own docs guide at /docs#reference",
		sidebar: "A sidebar entry opening this page",
		greetingLabel: "Show greeting",
		greetingHint: "Toggles the message on this plugin's page.",
		compactLabel: "Compact list",
		compactHint:
			"Demonstrates a second persisted setting (currently cosmetic).",
	},
	icons: {
		galleryTitle: "Icon Pack gallery",
		gallerySubtitle:
			"Everything this core plugin ships, fully offline — searchable Lucide, Font Awesome Solid and Brands, plus the bundled fonts. Click any icon to copy its SDK usage snippet.",
		fontsTab: "Fonts",
		searchLabel: "Search icons",
		searchPlaceholder: "e.g. home, circle-xmark, github …",
		loading: "Loading offline assets…",
		showing: "Showing {{shown}} of {{total}} ({{of}} total)",
		truncated: "Showing the first {{limit}} — refine your search to narrow it.",
		empty: "No icons match that search.",
	},
	// Story Renderer (v1.8.0) — core always-on plugin.
	storyRenderer: {
		exportTitle: "Export this story",
		markdown: "Markdown",
		markdownHint: "A .md file with the title, source, and full body.",
		html: "Themed HTML",
		htmlHint:
			"A single self-contained .html file with a clean editorial theme — works offline, opens anywhere.",
		png: "Screenshot (PNG)",
		pngHint: "The themed story rendered to a ready-to-share PNG image.",
		busy: "Preparing…",
		close: "Close",
		exportFailed: "The export failed — try again.",
		includeMetadataLabel: "Include story metadata",
		includeMetadataHint:
			"Source, author, date, and link at the top of every export.",
		preferTranslatedLabel: "Use the translated text",
		preferTranslatedHint:
			"When a translation exists, export it instead of the original.",
		viewTitle: "Story Renderer",
		viewIntro:
			"Story Renderer v{{version}} — a core, always-on plugin that reads any story as Markdown, a themed HTML page, or a ready-to-share screenshot.",
		viewFormats: "Formats",
	},
	// Copyright & Attribution (v1.8.0) — core always-on plugin.
	mediaCopyright: {
		includeAttributionLabel: "Add copyright attribution to downloads",
		includeAttributionHint:
			"Downloaded images credit the blog, article title, and source URL. Each download can still choose.",
		originalLabel: "Download originals",
		viewTitle: "Copyright & Attribution",
		viewIntro:
			"Copyright & Attribution v{{version}} — a core, always-on plugin that adds where-media-came-from credit to your downloads.",
		viewHow: "How downloads behave",
	},
	collections: {
		title: "Collections",
		subtitle:
			"Organize everything you collect into categories and folders — like a file explorer.",
		breadcrumbAria: "Breadcrumb",
		createFolderInside: "Create a folder inside this folder",
		createTopLevelCategory: "Create a top-level category",
		newFolder: "New folder",
		newCategory: "New category",
		newFolderIn: 'New folder in "{{name}}"',
		folderEmpty: "This folder is empty.",
		noCollectionsYet: "No collections yet.",
		collection: "collection",
		items: "Items",
		itemCount_one: "{{count}} item",
		itemCount_other: "{{count}} items",
		moveItemsInto: 'Move archive items into "{{name}}"',
		thisFolder: "this folder",
		addItems: "Add items",
		clickFolderHint:
			"Click a folder to see everything inside it — double-click to go inside.",
		loadingItems: "Loading items…",
		subfoldersHint:
			"No items directly in this folder — its sub-folders ({{folders}}) hold their own items. Double-click one to go inside.",
		noItemsHere:
			'No items here yet. Use "Add items" to move archive items into this folder.',
		showMore: "Show more ({{remaining}} remaining)",
		untitled: "Untitled",
		openItem: "Open item",
		moveToTrashTitle: 'Move "{{name}}" to Trash?',
		moveToTrashMessage:
			'The collection "{{name}}" and all its sub-folders are moved to the Trash — you can restore them from the Trash page. No stories or data are deleted.',
		moveToTrashConfirm: "Move to Trash",
		removeFromTitle: 'Remove from "{{name}}"?',
		removeFromMessage:
			'"{{title}}" will leave this collection. The item itself stays in your archive — nothing is deleted.',
		removeFromConfirm: "Remove from collection",
		thisItem: "This item",
		namePlaceholder: "Name…",
		nameAria: "Collection name",
		create: "Create",
		done: "Done",
		addItemsTo: 'Add items to "{{name}}"',
		searchItemsPlaceholder: "Search items to add…",
		searchItemsAria: "Search items",
		noMatchingItems: "No matching items.",
		typeToSearch: "Type to search your archive items.",
		add: "Add",
		folders_one: "{{count}} folder",
		folders_other: "{{count}} folders",
		items_one: "{{count}} item",
		items_other: "{{count}} items",
		empty: "Empty",
		rename: "Rename",
		delete: "Delete",
		categoryHint: "Category — click to select, double-click to open",
		folderHint: "Folder — click to select, double-click to open",
		actionsFor: "Actions for {{name}}",
		renameFor: "Rename {{name}}",
	},
	trash: {
		title: "Trash",
		subtitle:
			"Deleted collections and history entries live here — nothing is lost until you delete it forever.",
		body: "Deleting a collection or history entry moves it to the Trash instead of destroying it. After the retention window below, trashed entries are permanently deleted — saved items are never auto-deleted.",
		emptyTrash: "Empty trash",
		emptyTrashHint: "Permanently delete everything in the trash",
		emptyTrashConfirmTitle: "Empty trash?",
		retentionOff:
			"Trash is kept until you empty it (auto-delete is off in Settings → Trash).",
		retentionHint:
			"Entries are auto-deleted after {{value}} {{unit}} (Settings → Trash).",
		sectionRetentionOff:
			"0 keeps everything in the trash until you empty it. Currently off.",
		sectionRetentionHint:
			"e.g. 7 days removes trash entries older than 7 days. Currently {{value}} {{unit}}.",
		keepLabel: "Keep deleted items for",
		keepAria: "Keep deleted items for (value)",
		examplePlaceholder: "e.g. 7",
		unitAria: "Trash retention unit",
		apply: "Apply",
		entryCount_one: "{{count}} entry",
		entryCount_other: "{{count}} entries",
		emptyBody:
			"The trash is empty. Deleting a collection or history entry moves it here instead of destroying it.",
		deleteForeverTitle: 'Delete "{{name}}" forever?',
		purgeBookmarkedMessage_one:
			"{{count}} saved item inside will be permanently removed too — including its bookmark. This can't be undone.",
		purgeBookmarkedMessage_other:
			"{{count}} saved items inside will be permanently removed too — including its bookmark. This can't be undone.",
		purgeCollectionMessage:
			"The folder and its sub-folders are permanently removed. Stories inside move to uncategorized — no articles are deleted, but the organization is gone for good.",
		purgeEntryMessage:
			"The history entry and its cached data are permanently deleted. This can't be undone.",
		deleteForeverConfirm: "Delete forever",
		deleting: "Deleting…",
		emptyBookmarkedMessage_one:
			"{{count}} saved item in the trash will be permanently removed too — including their bookmarks. This can't be undone.",
		emptyBookmarkedMessage_other:
			"{{count}} saved items in the trash will be permanently removed too — including their bookmarks. This can't be undone.",
		emptyMessage:
			"Every entry in the trash is permanently deleted. This can't be undone.",
		emptying: "Emptying…",
		kindCollection: "Collection",
		kindSearch: "Search",
		kindBrief: "Briefing",
		kindGenerated: "Generated",
		typeBadgeTitle: "Type: {{label}}",
		deletedOn: "Deleted",
		savedCount_one: "{{count}} saved item",
		savedCount_other: "{{count}} saved items",
		restore: "Restore",
		restoreTitle: "Restore to its original place",
		permanentlyDelete: "Permanently delete",
	},
	bookmarks: {
		title: "Bookmarks",
		subtitle:
			"Stories and items you saved. Removing a bookmark never deletes the item itself.",
		emptyTitle: "No bookmarks yet",
		emptyBody:
			"Hit the bookmark icon on any story in the Brief to save it here.",
		goToBrief: "Go to Brief",
		savedItems: "Saved items",
		tipTitle: "Organize your saved items",
		tipBody:
			"Bookmarks also appear in the Archive — tag, note, and folder them",
		archiveLink: "Archive",
		removeTitle: "Remove bookmark?",
		removeMessage:
			"The item will be removed from Bookmarks. The story itself stays in the Archive — you can bookmark it again any time.",
		removeConfirm: "Remove bookmark",
		untitled: "Untitled",
	},
	changelogPage: {
		title: "Changelog",
		releaseNotes: "Release Notes",
		subtitle:
			"Less reading. More understanding. — every change that brought us here.",
		current: "Current",
		hideTechnical: "Hide technical details",
		showTechnical: "Show technical details",
		new: "New",
		improved: "Improved",
		fixed: "Fixed",
		security: "Security",
	},
	historyBrief: {
		notFound: "Briefing not found",
		notFoundBody:
			"This period summary may have been deleted or is no longer available.",
		storyCount_one: "{{count}} story",
		storyCount_other: "{{count}} stories",
		archived: "archived",
		showOriginalTitle:
			"Show the summary in the majority language of its stories",
		titleToday: "Today's Brief — {{count}} stories",
		titleWeek: "This Week's Brief — {{count}} stories",
		titleMonth: "This Month's Brief — {{count}} stories",
		titleAll: "All-Time Brief — {{count}} stories",
		themes: "Themes",
		takeaways: "Takeaways",
		recommendedActions: "Recommended Actions",
		aiGenerated: "AI-generated",
		regenerateOnBrief: "Regenerate on Brief",
		regenerate: "Regenerate",
		copyHeadline: "Copy headline",
		justNow: "just now",
		minAgo: "{{count}}m ago",
		hoursAgo: "{{count}}h ago",
		daysAgo: "{{count}}d ago",
		monthsAgo: "{{count}}mo ago",
		yearsAgo: "{{count}}y ago",
	},
	historyGenerated: {
		notFound: "Generation not found",
		notFoundBody:
			"This generated result may have been deleted or is no longer available.",
		backToProfile: "Back to Profile",
		tokens: "{{count}} tokens",
		tokensUsed: "{{count}} tokens used",
		archived: "archived",
		behaviorSummary: "Behavior Summary",
		improvedCustomInstruction: "Improved Custom Instruction",
		improvedInstruction: "Improved Instruction",
		instruction: "Instruction",
		regenerate: "Regenerate",
		improveAgain: "Improve again",
		copyText: "Copy text",
		justNow: "just now",
		minAgo: "{{count}}m ago",
		hoursAgo: "{{count}}h ago",
		daysAgo: "{{count}}d ago",
		monthsAgo: "{{count}}mo ago",
		yearsAgo: "{{count}}y ago",
	},
	historySearch: {
		notFound: "Search entry not found",
		notFoundBody:
			"This search result may have been deleted or is no longer available.",
		backToSearch: "Back to Search",
		hitCount_one: "{{count}} hit",
		hitCount_other: "{{count}} hits",
		tokens: "{{count}} tokens",
		reaskQuery: "Re-ask AI this query",
		researchQuery: "Re-search this query",
		answer: "Answer",
		citedSources_one: "{{count}} cited source",
		citedSources_other: "{{count}} cited sources",
		score: "score {{value}}",
		source: "Source",
		reask: "Re-ask AI",
		research: "Re-search",
		copyQuery: "Copy query",
		keyword: "Keyword",
		exportSourcesHeader: "Sources",
		justNow: "just now",
		minAgo: "{{count}}m ago",
		hoursAgo: "{{count}}h ago",
		daysAgo: "{{count}}d ago",
		monthsAgo: "{{count}}mo ago",
		yearsAgo: "{{count}}y ago",
	},
	period: {
		today: "Today",
		thisWeek: "This Week",
		thisMonth: "This Month",
		allTime: "All Time",
	},
	sort: {
		newest: "Newest",
		mostRelevant: "Most relevant",
		mostImportant: "Most important",
	},
	types: {
		article: "Story",
		summary: "Summary",
		"keyword-search": "Search",
		"ai-ask": "Ask AI",
		saved: "Saved",
		stories: "Stories",
		summaries: "Summaries",
		searches: "Searches",
		aiAsks: "AI asks",
	},
	scope: {
		global: "Global",
		regional: "Regional",
		national: "National",
		local: "Local",
		community: "Community",
	},
	authority: {
		official: "Official",
		research: "Research",
		community: "Community",
		media: "Media",
		aggregator: "Aggregator",
		personal: "Personal",
	},
	history: {
		closeAria: "Close history",
		howItWorks: "How History works",
		readDocs: "Read docs",
		titleBrief: "Briefing History",
		fromBrief: "from Today's Brief",
		titleGenerated: "Generated History",
		fromProfile: "from Profile",
		titleSearch: "Search History",
		tabViews: "Viewed stories",
		fromSearch: "from Search",
		entries: "{{count}} entries",
		select: "Select",
		done: "Done",
		noSearches: "No searches yet",
		noSearchesBody:
			"Run a keyword or Ask-AI search and it'll show up here. Ask-AI answers are saved by default; keyword recording can be enabled in Settings.",
		noBriefings: "No briefings saved",
		noBriefingsBody:
			"Generate a period summary from Today's Brief and it'll be saved here automatically, so you can revisit it without regenerating.",
		noGenerations: "No generations yet",
		noGenerationsBody:
			"Generate a behavior summary or improve a custom instruction from the Profile page and each one will be saved here.",
		hits: "{{count}} hits",
		tokens: "{{count}} tokens",
		archived: "archived",
		moreActions: "More actions",
		rename: "Rename",
		renameTitle: "Rename entry",
		unarchive: "Unarchive",
		archive: "Archive",
		delete: "Delete",
		deleteTitle: "Delete entry?",
		deleteMessage: "Delete this entry permanently?",
		deleteConfirm: "Delete",
		deleteManyTitle: "Delete {{count}} entries?",
		deleteManyMessage:
			"Delete {{count}} entries permanently? This cannot be undone.",
		selectHint: "Select entries to enable bulk actions",
		selectedCount: "{{count}} selected",
		periodToday: "Today",
		periodWeek: "Week",
		periodMonth: "Month",
		periodAll: "All",
		kindSummary: "Summary",
		kindInstruction: "Instruction",
		modeAi: "AI",
		modeKw: "KW",
		timeJustNow: "just now",
		timeMinutesAgo: "{{count}}m ago",
		timeHoursAgo: "{{count}}h ago",
		timeDaysAgo: "{{count}}d ago",
		timeMonthsAgo: "{{count}}mo ago",
		timeYearsAgo: "{{count}}y ago",
		recordBody:
			"Choose what gets saved to the History drawer. Saved entries can be renamed, archived, or deleted at any time.",
		recordAi: "Save Ask AI searches",
		recordAiHint:
			"Ask-AI answers cost tokens — keep them so you can revisit without re-running.",
		recordKeyword: "Save keyword searches",
		recordKeywordHint:
			"Keyword searches are fast and free — off by default to keep history focused.",
	},
	jobs: {
		title: "Jobs",
		running_one: "{{count}} job running",
		running_other: "{{count}} jobs running",
		active: "Active",
		noActive: "No active jobs.",
		recent: "Recent",
		refresh: "Refresh",
		cancel: "Cancel",
	},
	usage: {
		title: "Usage",
		reset: "Reset",
		totalRequests: "Total requests",
		failed: "{{count}} failed",
		totalTokens: "Total tokens",
		tokenBreakdown: "{{prompt}} in · {{completion}} out",
		last30Days: "Last 30 days",
		rateLimit: "Rate limit",
		spacing: "{{seconds}}s between requests",
		byOperation: "By operation",
		byProvider: "By provider",
		noData: "No data yet.",
		breakdownLine: "{{requests}} req · {{tokens}} tok",
		sinceHint:
			"Counts since {{date}}. Token counts are estimated (4 chars ≈ 1 token) when a provider doesn't expose metadata.",
	},
	retention: {
		title: "Auto-delete old stories",
		body: "Vorynth keeps everything by default. Turn this on to automatically remove stories after they get too old — independent of each source's time range.",
		enableLabel: "Auto-delete",
		olderThanDays:
			"Stories older than {{count}} days are removed (checked daily).",
		offHint: "Off — every collected story is kept.",
		deleteOlderThan: "Delete stories older than",
		deleteOlderThanAria: "Delete stories older than (days)",
		daysPlaceholder: "e.g. 30",
		days: "days",
		apply: "Apply",
		exampleHint:
			"e.g. 30 removes any story collected more than 30 days ago. 0 turns auto-delete off.",
		neverDelete: "Never delete",
		protectBookmarked: "Bookmarked stories",
		protectBookmarkedHint:
			"A bookmark is your ownership of a reference (R-A10).",
		protectInCollection: "Stories in collections",
		protectInCollectionHint:
			"Anything you placed in a folder or category stays.",
	},
	trashUnits: {
		days: "Days",
		weeks: "Weeks",
		months: "Months",
		years: "Years",
	},
	dataOwnership: {
		body: "Your data lives in a local SQLite file. Export a backup, restore from one, or permanently delete everything.",
		backups: "Backups",
		removeBackup: "Remove backup",
		exporting: "Exporting…",
		sure: "Sure?",
		deleting: "Deleting…",
		deleteEverything: "Yes, delete everything",
		exported: "Backup exported: {{path}} ({{size}} KB)",
		exportFailed: "Export failed: {{message}}",
		restoreFailed: "Restore failed: {{message}}",
		deleteFailed: "Delete failed: {{message}}",
		// v1.8.0 — backups list is always visible: empty state + per-file
		// download (save to Downloads) and flavor labels.
		noBackups: "No backups yet — create one with Export below.",
		download: "Save to Downloads",
		downloading: "Saving…",
		downloaded: "Saved to your Downloads folder.",
		downloadFailed: "Download failed: {{message}}",
		kindEngine: "Engine backup",
		kindSqlite: "SQLite copy",
	},
	typeBadge: {
		title: "Type: {{label}}",
	},
	docsHelp: {
		howItWorks: "How it works",
	},
	periodSummary: {
		periodToday: "today",
		periodWeek: "this week",
		periodMonth: "this month",
		recently: "recently",
		title: "Period Briefing",
		intro: "One cohesive intelligence summary over {{period}}'s stories.",
		summarize: "Summarize {{period}}",
		summarizing: "Summarizing…",
		showOriginalHint:
			"Show the summary in the majority language of its stories",
		runningHint:
			"Running in the background — you can navigate away; the result appears here.",
		takeaways: "Takeaways",
		moreInFullBrief: "+{{count}} more in the full brief",
		basedOn: "Based on {{count}} stories from {{period}}.",
		openFullBrief: "Open the full briefing",
		fullBriefUnavailable: "Full brief unavailable",
		viewFullBrief: "View full brief",
	},
	summaryLanguage: {
		auto: "Auto (majority of the stories)",
	},
	attribution: {
		copyright: "©",
		source: "Source: ",
	},
	insight: {
		sourceLanguage: "Source language",
		outputLanguage: "Output language",
		generated: "Generated",
		mixed: "Mixed",
	},
	llmError: {
		notConfigured:
			"No AI provider is configured. Add one in Settings to use AI features.",
		keyMissing:
			"The active AI provider has no API key. Re-enter it in Settings.",
		keyUndecryptable:
			"The AI provider's API key can't be decrypted. Remove the provider and add it again in Settings.",
		authFailed:
			"The AI provider rejected the API key. Check it in Settings and try again.",
		rateLimited:
			"The AI provider is rate-limiting requests. Wait a moment and try again.",
		unreachable:
			"Couldn't reach the AI provider. Check your connection and try again.",
		error: "The AI request failed. Try again.",
	},
	// v1.8.0 — global auto-update banner.
	updates: {
		bannerTitle: "Update available — Vorynth {{version}} is ready",
		bannerAction: "Download & install",
		bannerDownloading: "Downloading…",
		bannerInstalling: "Installing… Vorynth will restart",
		bannerDismiss: "Dismiss",
		bannerError: "The update check failed.",
	},
	// v1.8.0 — notification center.
	notifications: {
		aria: "Notifications",
		title: "Notifications",
		markAllRead: "Mark all read",
		clear: "Clear",
		empty: "No notifications yet",
		unread: "Unread",
		justNow: "Just now",
		minutesAgo: "{{count}}m ago",
		hoursAgo: "{{count}}h ago",
		daysAgo: "{{count}}d ago",
		jobDoneTitle: "Job finished",
		jobFailedTitle: "Job failed",
		updateTitle: "Update available — Vorynth {{version}}",
		updateBody: "A newer version is ready to install.",
	},
};

export type TranslationCatalog = typeof en;
