import type { DocsSection } from "../types.js";

/** Archive — the unified user-owned intelligence space. */
export const archiveSection: DocsSection = {
	id: "archive",
	title: "Archive",
	summary: "Everything Vorynth has collected, organized your way.",
	icon: "inventory_2",
	pageRoute: "/archive",
	blocks: [
		{
			type: "paragraph",
			text: "The Archive is one space for every item Vorynth has produced: collected stories, saved (bookmarked) items, generated summaries, keyword searches, and Ask-AI answers. It's your personal intelligence space — everything you can search, tag, note, and organize.",
		},
		{
			type: "paragraph",
			text: "Why one space: your knowledge shouldn't be scattered across features. Whether a story was collected automatically, saved by hand, or generated by the AI, it's the same kind of thing here — an item you own — so it can be searched, tagged, noted, and organized with the same tools. Nothing is lost between features; everything you can't delete, you can find.",
		},
		{
			type: "flow",
			title: "The lifecycle of an item",
			steps: [
				{ icon: "cloud_download", label: "Collect" },
				{ icon: "bookmark", label: "Save" },
				{ icon: "create_new_folder", label: "Organize" },
				{ icon: "search", label: "Find" },
			],
		},
		{
			type: "features",
			items: [
				{
					icon: "folder_special",
					label: "Collections page",
					text: "Organizing lives on its own page — categories (semantic roots) and folders (max depth 3) in a Windows-Explorer style icon view: big folder cards (each showing its sub-folder and item counts), a breadcrumb, and the selected folder's items listed below. Reach it from the Archive section tabs (Items · Collections · Bookmarks · Search · Trash) shown on every Archive page — see the Collections docs.",
				},
				{
					icon: "edit_note",
					label: "Open an item",
					text: "Every item opens its full detail page when clicked: stories open the article reader, summaries the briefing detail, and searches or AI asks the cached result. Back returns you to exactly where you were.",
				},
				{
					icon: "folder",
					label: "Move to a collection",
					text: "Each item row has a Move-to-collection selector to file it into a folder, or move it back to uncategorized. Organize at scale on the Collections page.",
				},
				{
					icon: "filter_list",
					label: "Items list",
					text: "Type filters with icons (All / Stories / Saved / Summaries / Searches / AI asks), a text filter by title or note, and a 'Show archived' toggle. Paginated — 'Show more' loads the next batch.",
				},
				{
					icon: "edit_note",
					label: "Notes & tags",
					text: "Every item can carry a free-form note and tags; both are searchable from the filter box.",
				},
			],
		},
		{
			type: "bullets",
			items: [
				"A story opens the article reader; a summary opens the briefing detail; a search or AI ask opens the full cached result.",
				"Bookmarks get their own page and also appear under 'Saved' in the Archive.",
				"Save, Note, and Archive actions live on each item row.",
				"Naming: a folder and a category with the same name can sit side by side (they're different types). Two folders — or two categories — with the same name in the same place are refused.",
			],
		},
	],
};
