import { VORYNTH_VERSION } from "@vorynth/types";
import type { PlatformKey } from "./download";

/** Numeric version is single-sourced from `@vorynth/types` — no drift.
 *  The codename is a hand-maintained brand string (same as the README). */
export const VERSION = VORYNTH_VERSION;
export const CODENAME = "Privacy First";
export const RELEASES_URL = "https://github.com/omidnw/vorynth/releases";

export interface Feature {
	icon: string;
	title: string;
	body: string;
}

export const FEATURES: Feature[] = [
	{
		icon: "hub",
		title: "Collect from your sources",
		body: "RSS feeds, GitHub releases, arXiv papers, and more \u2014 if it publishes updates, Vorynth brings it into one quiet place.",
	},
	{
		icon: "auto_awesome",
		title: "Intelligence mode",
		body: "Why it matters, impact, and a recommended action for every story \u2014 generated by your choice of four LLM providers.",
	},
	{
		icon: "newspaper",
		title: "News mode, no key needed",
		body: "A ranked feed that works with zero API key and zero setup. Add AI later, whenever you want it.",
	},
	{
		icon: "forum",
		title: "Ask in plain language",
		body: "Type a question and get an answer drawn from everything collected \u2014 with clickable citations back to the sources.",
	},
	{
		icon: "folder_open",
		title: "An archive you own",
		body: "Stories, saved items, summaries, searches, and AI asks in one place \u2014 organized with collections, folders, tags, and notes.",
	},
	{
		icon: "search",
		title: "Search everything",
		body: "Blazing-fast full-text search across every collected article \u2014 Persian-safe, instant, and never locked in a cloud cache.",
	},
	{
		icon: "shield",
		title: "Private by design",
		body: "A local database, no cloud account, no telemetry \u2014 with one-click backup and restore whenever you want peace of mind.",
	},
];

export interface OriginStep {
	icon: string;
	title: string;
	body: string;
}

/** The problem Vorynth exists to solve — shown line by line. */
export const ORIGIN_INTRO = [
	"Every day, thousands of important articles, papers, and updates are published.",
	"The problem is not finding information.",
	"The problem is understanding what actually matters.",
];

export const ORIGIN_IDEA =
	"What if I could collect the sources I trust, remove the noise, and spend 10 minutes every day understanding what changed?";

/** How a personal idea grew into an intelligence engine. */
export const ORIGIN_STEPS: OriginStep[] = [
	{
		icon: "newspaper",
		title: "A better way to read the news",
		body: "Vorynth began as one place to collect the news you actually follow \u2014 and read it without the noise.",
	},
	{
		icon: "school",
		title: "Then the research world found it",
		body: "A conversation with a university researcher revealed the same problem in academia: following papers, tracking fields, and organizing knowledge.",
	},
	{
		icon: "auto_stories",
		title: "Then it made reading enjoyable",
		body: "Vorynth grew features that turn dense text into something you can read without feeling lost \u2014 context, summaries, and a clean reading layout.",
	},
];

export const ORIGIN_OUTRO =
	"Today, Vorynth helps engineers, researchers, and curious minds turn information overload into a focused intelligence brief \u2014 a few minutes a day, all on your machine.";

export interface Audience {
	icon: string;
	name: string;
	label: string;
	items: string[];
}

export const AUDIENCE: Audience[] = [
	{
		icon: "code",
		name: "Engineers",
		label: "Stay updated with",
		items: [
			"Framework changes",
			"Releases",
			"Security alerts",
			"AI developments",
		],
	},
	{
		icon: "science",
		name: "Researchers",
		label: "Follow",
		items: [
			"Papers and publications",
			"Emerging fields",
			"Field discussions",
			"Research workflows",
		],
	},
	{
		icon: "lightbulb",
		name: "Curious minds",
		label: "Understand",
		items: ["What changed", "Why it matters", "Where things are going"],
	},
];

export interface NotAiPoint {
	icon: string;
	text: string;
}

/** "Not another AI chat window" — the four things Vorynth is built around. */
export const NOT_AI: { points: NotAiPoint[]; closing: string } = {
	points: [
		{ icon: "rss_feed", text: "Your sources" },
		{ icon: "folder_open", text: "Your archive" },
		{ icon: "history", text: "Your reading history" },
		{ icon: "psychology", text: "Your intelligence workflow" },
	],
	closing:
		"Everything is stored locally on your device \u2014 Vorynth works alongside your AI assistant, not instead of it.",
};

export interface Faq {
	q: string;
	a: string;
	/** One-line takeaway shown as a highlighted callout under the answer. */
	key?: string;
}

export const FAQ: Faq[] = [
	{
		q: "What is Vorynth?",
		a: "Vorynth is a local-first personal intelligence engine that collects information from your trusted sources, ranks what matters, and optionally uses AI to explain why it matters. It is designed for engineers, researchers, and anyone who wants to stay updated without spending hours reading everything.",
	},
	{
		q: "Why is Vorynth local-first?",
		a: "Because your information is yours. Local-first means Vorynth runs entirely on your device: collected articles, reading history, notes, sources, settings, and API keys are stored locally and stay under your control. There is no cloud account, no telemetry, and nothing is shared unless you explicitly send it to an AI provider. For researchers and organizations, keeping research data on their own machines isn\u2019t a preference \u2014 it\u2019s a requirement.",
	},
	{
		q: "Why not just use ChatGPT, Claude, or Gemini?",
		a: "Different tools, different purposes. General AI assistants are excellent for answering questions, but Vorynth is built around your own sources, your own archive, your own reading history, and your own workflow. Everything is stored locally on your device, and you choose when \u2014 or if \u2014 an AI provider is used. Some people don\u2019t want their information in big-company AI products, and many universities and organizations can\u2019t allow research data to be shared with them. Certifications like SOC 2 reduce risk, but they can never give you certainty about how your data is used. Vorynth removes the question: your data never leaves your device unless you send it.",
		key: "Your data never leaves your device.",
	},
	{
		q: "Does Vorynth replace AI assistants?",
		a: "No. Vorynth works alongside AI assistants. Think of it as your personal information layer: sources in, understanding out. AI assistants answer questions; Vorynth helps you know which questions are worth asking.",
	},
	{
		q: "Do I need an AI API key?",
		a: "No \u2014 Vorynth works without one, but a key unlocks the features that make it really useful. **News mode needs no API key: collect, rank, read, search, and archive \u2014 all on your device.** Add your own provider key and the advanced features turn on \u2014 **translations, AI summaries (why it matters, impact, recommended action), plain-language questions with citations, and the Behavior Summary.** Supported providers: Gemini, OpenAI, Anthropic, and Ollama. Without a key, Vorynth is a clean, private news reader; with one, it explains and translates for you.",
		key: "News mode: no key. Intelligence mode: optional.",
	},
	{
		q: "Where is my data stored?",
		a: "On your machine. Vorynth stores collected articles, reading history, notes, sources, settings, and API keys locally. There is no mandatory account and no required cloud synchronization.",
		key: "No mandatory account, no required cloud sync.",
	},
	{
		q: "Can universities or researchers use Vorynth?",
		a: "Yes. Vorynth was partly shaped by conversations around research workflows. Researchers can follow papers, track developments in their field, monitor new trends, and organize knowledge. Because Vorynth is local-first, universities and research groups keep full control over their collected information \u2014 research data doesn\u2019t enter a third-party AI product unless they opt in.",
		key: "Research data stays under your control.",
	},
	{
		q: "Is Vorynth only for software engineers?",
		a: "No. Software engineering is the starting point, because that\u2019s where Vorynth was born. The architecture supports other domains \u2014 research, science, security, finance, medicine, and any field with reliable information sources.",
	},
	{
		q: "Does Vorynth scrape websites?",
		a: "Vorynth prefers legitimate public sources: RSS feeds, public APIs, sitemaps, and public JSON endpoints. Official connectors are built only for sources with a legitimate public access path, and community connectors can extend support for additional sources.",
	},
	{
		q: "Is Vorynth open source?",
		a: "Yes. The source code is available under the MIT license. You can inspect how the application works, build from source, and contribute improvements.",
	},
	{
		q: "Can I backup or delete my data?",
		a: "Yes. Your data belongs to you. You can back up your local database, restore your data, and delete your collected information \u2014 no account required.",
	},
	{
		q: "Is there a mobile version?",
		a: "Not yet \u2014 Vorynth is a desktop app. We have no plan for phone support at the moment, but it will likely be added in the future.",
	},
];

export interface WhyItem {
	icon: string;
	title: string;
	body: string;
}

export const WHY: WhyItem[] = [
	{
		icon: "radar",
		title: "Signal over noise",
		body: "The goal isn\u2019t collecting everything \u2014 it\u2019s finding what matters. Every story is importance-ranked, not just time-sorted.",
	},
	{
		icon: "fact_check",
		title: "Explain, don't just summarize",
		body: "A summary answers \u201cwhat happened?\u201d Vorynth answers what happened, why it matters, and what to do about it.",
	},
	{
		icon: "verified",
		title: "Source quality over quantity",
		body: "A handful of sources you trust beats a thousand you don\u2019t. Curated lists and per-source controls keep the noise out.",
	},
	{
		icon: "lock",
		title: "Private by design",
		body: "Local-first storage, no account, no telemetry. Your sources, history, and keys never leave your machine.",
	},
];

export interface Step {
	icon: string;
	step: string;
	title: string;
	body: string;
}

export const STEPS: Step[] = [
	{
		icon: "rss_feed",
		step: "Step 1 \u00b7 Collect",
		title: "Your sources, fetched",
		body: "Six adapters \u2014 RSS, GitHub releases, arXiv, HTML crawling, Sitemaps, and JSON APIs \u2014 plus curated lists you enable in one click.",
	},
	{
		icon: "filter_alt",
		step: "Step 2 \u00b7 Normalize & rank",
		title: "Signal floats up",
		body: "Every item is deduplicated, classified, and importance-scored \u2014 so the stories that matter today sit on top, not the noisiest feed.",
	},
	{
		icon: "psychology",
		step: "Step 3 \u00b7 Understand",
		title: "Why it matters",
		body: "The AI triad \u2014 why it matters, impact, and a recommended action \u2014 generated from your choice of four LLM providers.",
	},
	{
		icon: "campaign",
		step: "Step 4 \u00b7 Deliver",
		title: "A brief you own",
		body: "Skim the daily brief in minutes, search everything, ask questions with citations, and file it all in your archive \u2014 all on-device.",
	},
];

export interface Mode {
	featured: boolean;
	tone: "news" | "ai";
	tag: string;
	title: string;
	desc: string;
	bullets: string[];
}

export const MODES: Mode[] = [
	{
		featured: false,
		tone: "news",
		tag: "News mode \u00b7 no key",
		title: "A ranked feed that just works",
		desc: "Vorynth collects, ranks, and serves a clean brief with zero configuration \u2014 no API key required, ever.",
		bullets: [
			"Importance-ranked feed from your sources",
			"Search, archive, and backups included",
			"Fully offline once sources are collected",
		],
	},
	{
		featured: true,
		tone: "ai",
		tag: "Intelligence mode \u00b7 optional",
		title: "Add the AI triad any time",
		desc: "Bring your own API key and Vorynth explains each story \u2014 why it matters, its impact, and a recommended action.",
		bullets: [
			"Why it matters / Impact / Recommended action per story",
			"Ask questions in plain language, answered with citations",
			"Four providers: OpenAI, Anthropic, Gemini, Ollama",
		],
	},
];

export interface Stat {
	icon: string;
	value: string;
	label: string;
	/** Optional landing-internal target — the card becomes a link. */
	href?: string;
}

export const STATS: Stat[] = [
	{
		icon: "rss_feed",
		value: "24",
		label: "Curated Feeds in the Starter List",
		href: "sources/developer/",
	},
	{ icon: "hub", value: "6", label: "Source Adapters" },
	{ icon: "smart_toy", value: "4", label: "LLM Providers" },
	{ icon: "shield", value: "100%", label: "Local & Private" },
];

export interface Platform {
	icon: string;
	name: string;
	status: string;
	tone: "native" | "source";
	/** Maps to a release-asset filter; "harmony" has no native installer. */
	key: PlatformKey | "harmony";
}

export const PLATFORMS: Platform[] = [
	{
		icon: "desktop_mac",
		name: "macOS",
		status: "Apple Silicon + Intel",
		tone: "native",
		key: "mac",
	},
	{
		icon: "window",
		name: "Windows",
		status: "x86_64 + ARM64",
		tone: "native",
		key: "windows",
	},
	{
		icon: "terminal",
		name: "Linux",
		status: "x86_64 + ARM64",
		tone: "native",
		key: "linux",
	},
	{
		icon: "dns",
		name: "FreeBSD",
		status: "x86_64",
		tone: "native",
		key: "freebsd",
	},
	{
		icon: "globe",
		name: "Harmony OS",
		status: "Experimental \u00b7 raw bundle",
		tone: "source",
		key: "harmony",
	},
];

export interface TopicLink {
	/** Relative to BASE_URL — e.g. "ai-news-reader/" or "sources/developer/". */
	href: string;
	label: string;
	note?: string;
}

export interface TopicSection {
	heading: string;
	body: string;
	bullets?: string[];
}

export interface TopicPageData {
	slug: string;
	/** Small eyebrow label above the h1. */
	label: string;
	/** The h1 — carries the page's target keyword. */
	title: string;
	sub: string;
	intro: string;
	sections: TopicSection[];
	related: TopicLink[];
}

/**
 * Keyword landing pages. Every word here describes a REAL product capability —
 * no invented stats, no ratings, no opinions (R-C04). These are informational
 * pages that internal-link to each other, the home page, and the real curated
 * source lists.
 */
export const TOPIC_PAGES: Record<string, TopicPageData> = {
	"ai-news-reader": {
		slug: "ai-news-reader",
		label: "AI news reader",
		title: "AI News Reader",
		sub: "The news-reading side of Vorynth, a personal intelligence engine \u2014 collect the stories from sources you trust, rank what matters, and understand each one: why it matters, its impact, and what to do.",
		intro:
			"Vorynth is a personal intelligence engine, and reading the news is one of the things it does well. It brings RSS feeds, GitHub releases, arXiv papers, and more into one place, ranks them by importance, and uses AI to explain each story instead of just listing headlines.",
		sections: [
			{
				heading: "Collect the news you care about",
				body: "Six source adapters \u2014 RSS, GitHub releases, arXiv, HTML crawling, Sitemaps, and JSON APIs \u2014 plus curated lists you enable in one click. If a source publishes updates, Vorynth can read it.",
			},
			{
				heading: "AI explains each story",
				body: "For every story, the AI triad answers three questions: why it matters, its impact, and a recommended action. The analysis is generated by the LLM provider you choose \u2014 OpenAI, Anthropic, Gemini, or Ollama.",
			},
			{
				heading: "Ask AI about your news",
				body: "Type a question in plain language and Vorynth answers from everything it has collected, with clickable citations back to the source stories.",
			},
			{
				heading: "Works without an API key",
				body: "News mode gives you the ranked, searchable feed with zero setup and no API key. Add a provider key later to turn on AI analysis, translations, and plain-language answers.",
			},
			{
				heading: "Private by design",
				body: "Everything runs locally \u2014 your database, your reading history, and your AI keys stay on your device. No cloud account, no telemetry.",
			},
		],
		related: [
			{
				href: "personal-intelligence/",
				label: "Personal Intelligence Engine",
				note: "the full Vorynth vision",
			},
			{
				href: "local-first/",
				label: "Local-First News Reader",
				note: "why everything stays on your device",
			},
			{
				href: "rss-reader/",
				label: "RSS Reader & News Aggregator",
				note: "the six source adapters in detail",
			},
			{
				href: "sources/developer/",
				label: "24 Developer RSS Feeds",
				note: "the official starter list, in full",
			},
			{ href: "", label: "Back to the home page" },
		],
	},
	"personal-intelligence": {
		slug: "personal-intelligence",
		label: "Personal intelligence",
		title: "Personal Intelligence Engine",
		sub: "Turn information overload into understanding \u2014 Vorynth collects what matters, adds context, and helps you decide. A personal intelligence layer that lives on your device.",
		intro:
			"Where a news reader shows you headlines and a search engine hands you results, Vorynth works through the chain that actually matters: information \u2192 context \u2192 understanding \u2192 decision. Every day it collects from the sources you trust, ranks what changed, and explains why it matters and what to do.",
		sections: [
			{
				heading: "Information is abundant, understanding is scarce",
				body: "The problem isn't finding information \u2014 it's knowing what matters, why it matters, what it changes, and whether you should act. Vorynth's pipeline (collect \u2192 normalize \u2192 rank \u2192 analyze \u2192 brief) is built around exactly that problem.",
			},
			{
				heading: "Context, not just summaries",
				body: "A summary answers what happened. Vorynth answers what happened, why it matters, its impact, and a recommended action \u2014 the AI triad, generated from the LLM provider you choose.",
			},
			{
				heading: "Decisions, not feeds",
				body: "Ask a question in plain language and get an answer drawn from everything collected, with citations. Daily, weekly, and monthly briefs surface what changed and what deserves your attention.",
			},
			{
				heading: "Your knowledge belongs to you",
				body: "Everything \u2014 sources, archive, history, AI keys \u2014 lives in a local database on your device. No cloud account, no telemetry, one-click backup and restore.",
			},
			{
				heading: "AI that augments you, not replaces you",
				body: "You choose the model \u2014 OpenAI, Anthropic, Gemini, or a self-hosted Ollama \u2014 and the analysis is a starting point for your own thinking, never a replacement for it.",
			},
		],
		related: [
			{
				href: "ai-news-reader/",
				label: "AI News Reader",
				note: "news, explained by AI",
			},
			{
				href: "rss-reader/",
				label: "RSS Reader & News Aggregator",
				note: "the six source adapters",
			},
			{
				href: "local-first/",
				label: "Local-First News Reader",
				note: "your data stays on your device",
			},
			{
				href: "open-source/",
				label: "Open Source News Reader",
				note: "MIT licensed, on GitHub",
			},
			{
				href: "sources/developer/",
				label: "24 Developer RSS Feeds",
				note: "the official starter list",
			},
			{ href: "", label: "Back to the home page" },
		],
	},
	"local-first": {
		slug: "local-first",
		label: "Local-first",
		title: "Local-First News Reader",
		sub: "A news reader where your data never leaves your device \u2014 no cloud account, no telemetry, no lock-in.",
		intro:
			"Local-first means the application treats your machine as the source of truth. Vorynth stores everything in a local database on your computer, works offline once sources are collected, and never requires an account or cloud synchronization.",
		sections: [
			{
				heading: "Your data never leaves your device",
				body: "Stories, saved items, searches, AI questions, and your LLM API keys all live in a local database on your machine. There is no mandatory account and no required cloud sync.",
			},
			{
				heading: "Works offline",
				body: "Once sources are collected, the ranked feed, search, and archive are fully available offline.",
			},
			{
				heading: "You own your archive",
				body: "Every story, bookmark, summary, and answer is yours \u2014 organized with collections, folders, tags, and notes, and protected by one-click backup and restore.",
			},
			{
				heading: "For researchers and security-conscious readers",
				body: "Keeping research data on your own machine isn't a preference \u2014 for many institutions it's a requirement. Vorynth's local-first design keeps research data under your control.",
			},
		],
		related: [
			{
				href: "personal-intelligence/",
				label: "Personal Intelligence Engine",
				note: "the full Vorynth vision",
			},
			{
				href: "ai-news-reader/",
				label: "AI News Reader",
				note: "the AI analysis side of Vorynth",
			},
			{
				href: "open-source/",
				label: "Open Source News Reader",
				note: "MIT licensed \u2014 inspect everything",
			},
			{ href: "", label: "Back to the home page" },
		],
	},
	"rss-reader": {
		slug: "rss-reader",
		label: "RSS reader",
		title: "RSS Reader & News Aggregator",
		sub: "An RSS reader that aggregates feeds, GitHub releases, arXiv papers, and more into one ranked, searchable, AI-readable stream.",
		intro:
			"Vorynth is an RSS reader that grew into a full news aggregator: six source adapters collect from feeds and structured endpoints, every item is deduplicated and importance-ranked, and the result is a daily brief instead of a thousand tabs.",
		sections: [
			{
				heading: "Six source adapters",
				body: "RSS feeds, GitHub releases, arXiv, HTML crawling, Sitemaps, and JSON APIs. For sites with no feed at all, the HTML crawler extracts stories from a listing page using CSS selectors.",
			},
			{
				heading: "Start from curated lists",
				body: "The official starter list ships 24 stable developer feeds \u2014 AI, programming, web, backend, devops, cloud, security, and open source \u2014 plus Kubernetes and security lists. Enable one and collect immediately.",
			},
			{
				heading: "Search everything",
				body: "Full-text search over every collected article, powered by SQLite FTS5 \u2014 instant and Persian-safe, with no cloud cache.",
			},
			{
				heading: "Organize your archive",
				body: "Collections, folders, tags, notes, bookmarks, and reading history keep the archive yours. The daily brief and period summaries (daily, weekly, monthly) surface what changed.",
			},
		],
		related: [
			{
				href: "personal-intelligence/",
				label: "Personal Intelligence Engine",
				note: "the full Vorynth vision",
			},
			{
				href: "sources/developer/",
				label: "24 Developer RSS Feeds",
				note: "the full starter list",
			},
			{
				href: "sources/kubernetes/",
				label: "Kubernetes News Sources",
				note: "Kubernetes & Cloud Native feeds",
			},
			{
				href: "sources/security/",
				label: "Security News Sources",
				note: "infosec advisories & threat research",
			},
			{
				href: "ai-news-reader/",
				label: "AI News Reader",
				note: "add AI analysis on top of the feed",
			},
			{ href: "", label: "Back to the home page" },
		],
	},
	"open-source": {
		slug: "open-source",
		label: "Open source",
		title: "Open Source News Reader",
		sub: "MIT-licensed, on GitHub, and extensible \u2014 inspect the code, run it from source, bring your own LLM, and keep your intelligence workflow yours.",
		intro:
			"Vorynth is open source under the MIT license. The desktop app, the core engine, and the landing site are all public on GitHub \u2014 you can read the code, build from source, and audit exactly what runs on your machine.",
		sections: [
			{
				heading: "MIT licensed",
				body: "Released under the MIT license \u2014 inspect it, modify it, and use it in your own projects.",
			},
			{
				heading: "Run it your way",
				body: "Clone the repository and run from source, or download a packaged release for macOS, Windows, Linux, or FreeBSD.",
			},
			{
				heading: "Bring your own LLM",
				body: "Use OpenAI, Anthropic, or Gemini \u2014 or point Vorynth at a self-hosted Ollama instance so even the AI runs on your hardware.",
			},
			{
				heading: "Extensible with plugins",
				body: "Adapter plugins add new source types; UI plugins extend the reading experience. Installed plugins pass a security scan before they are enabled.",
			},
		],
		related: [
			{
				href: "personal-intelligence/",
				label: "Personal Intelligence Engine",
				note: "the full Vorynth vision",
			},
			{
				href: "local-first/",
				label: "Local-First News Reader",
				note: "where your data lives",
			},
			{
				href: "ai-news-reader/",
				label: "AI News Reader",
				note: "the AI analysis side of Vorynth",
			},
			{ href: "", label: "Back to the home page" },
		],
	},
};

export interface Screenshot {
	/** Filename inside public/screenshots/ — served at BASE_URL + screenshots/. */
	src: string;
	/** Descriptive alt text (also the SEO/accessibility description). */
	alt: string;
	/** Visible caption under the image. */
	caption: string;
}

/** The screenshot gallery — filenames/captions match the real screenshots the
 *  project ships (docs-less: the files live in apps/landing/public/screenshots/). */
export const SCREENSHOTS: Screenshot[] = [
	{
		src: "todays-brief.png",
		alt: "Today's Intelligence Brief — the ranked news feed",
		caption: "Today's Brief — the ranked feed, with AI context on every story",
	},
	{
		src: "welcome.png",
		alt: "Vorynth welcome screen during first-run setup",
		caption: "Welcome — the first-run setup screen",
	},
	{
		src: "sources.png",
		alt: "Sources page for managing feeds and curated lists",
		caption: "Sources — add your own feeds and enable curated lists",
	},
	{
		src: "sources-2.png",
		alt: "Sources page showing curated lists",
		caption: "Sources — curated lists, ready in one click",
	},
	{
		src: "article-view.png",
		alt: "Article reading view",
		caption: "Article view — read the full story in the reader",
	},
	{
		src: "story-article-view.png",
		alt: "Story in the article reading view",
		caption: "Story — opened in the article reading view",
	},
	{
		src: "story-insight-view.png",
		alt: "Story with the AI insight panel",
		caption: "Story — the AI insight: why it matters, impact, and what to do",
	},
	{
		src: "insight-view.png",
		alt: "Insight view of a story",
		caption: "Insight view — the AI triad for a story",
	},
	{
		src: "insight-view-2.png",
		alt: "Insight view, continued",
		caption: "Insight view — the analysis, continued",
	},
	{
		src: "archive-items.png",
		alt: "Archive with collections, folders, tags, and notes",
		caption: "Archive — collections, folders, tags, and notes",
	},
	{
		src: "docs.png",
		alt: "In-app documentation page",
		caption: "In-app documentation — every page and option explained",
	},
	{
		src: "jobs.png",
		alt: "Background jobs panel",
		caption: "Background jobs — collection and analysis progress",
	},
	{
		src: "jobs-2.png",
		alt: "Background jobs panel with task statuses",
		caption: "Background jobs — the status of every task",
	},
];
