import { VORYNTH_VERSION } from "@vorynth/types";
import type { PlatformKey } from "./download";

/** Numeric version is single-sourced from `@vorynth/types` — no drift.
 *  The codename is a hand-maintained brand string (same as the README). */
export const VERSION = VORYNTH_VERSION;
export const CODENAME = "Extend The Signal";
export const RELEASES_URL = "https://github.com/omidnw/vorynth/releases";

export interface Feature {
	icon: string;
	title: string;
	body: string;
}

export const FEATURES: Feature[] = [
	{
		icon: "hub",
		title: "Collect from your sources",
		body: "RSS feeds, GitHub releases, arXiv papers, and more \u2014 if it publishes updates, Vorynth brings it into one quiet place.",
	},
	{
		icon: "auto_awesome",
		title: "Intelligence mode",
		body: "Why it matters, impact, and a recommended action for every story \u2014 generated by your choice of four LLM providers.",
	},
	{
		icon: "newspaper",
		title: "News mode, no key needed",
		body: "A ranked feed that works with zero API key and zero setup. Add AI later, whenever you want it.",
	},
	{
		icon: "forum",
		title: "Ask in plain language",
		body: "Type a question and get an answer drawn from everything collected \u2014 with clickable citations back to the sources.",
	},
	{
		icon: "folder_open",
		title: "An archive you own",
		body: "Stories, saved items, summaries, searches, and AI asks in one place \u2014 organized with collections, folders, tags, and notes.",
	},
	{
		icon: "search",
		title: "Search everything",
		body: "Blazing-fast full-text search across every collected article \u2014 Persian-safe, instant, and never locked in a cloud cache.",
	},
	{
		icon: "shield",
		title: "Private by design",
		body: "A local database, no cloud account, no telemetry \u2014 with one-click backup and restore whenever you want peace of mind.",
	},
];

export interface OriginStep {
	icon: string;
	title: string;
	body: string;
}

/** The problem Vorynth exists to solve — shown line by line. */
export const ORIGIN_INTRO = [
	"Every day, thousands of important articles, papers, and updates are published.",
	"The problem is not finding information.",
	"The problem is understanding what actually matters.",
];

export const ORIGIN_IDEA =
	"What if I could collect the sources I trust, remove the noise, and spend 10 minutes every day understanding what changed?";

/** How a personal idea grew into an intelligence engine. */
export const ORIGIN_STEPS: OriginStep[] = [
	{
		icon: "newspaper",
		title: "A better way to read the news",
		body: "Vorynth began as one place to collect the news you actually follow \u2014 and read it without the noise.",
	},
	{
		icon: "school",
		title: "Then the research world found it",
		body: "A conversation with a university researcher revealed the same problem in academia: following papers, tracking fields, and organizing knowledge.",
	},
	{
		icon: "auto_stories",
		title: "Then it made reading enjoyable",
		body: "Vorynth grew features that turn dense text into something you can read without feeling lost \u2014 context, summaries, and a clean reading layout.",
	},
];

export const ORIGIN_OUTRO =
	"Today, Vorynth helps engineers, researchers, and curious minds turn information overload into a focused intelligence brief \u2014 a few minutes a day, all on your machine.";

export interface Audience {
	icon: string;
	name: string;
	label: string;
	items: string[];
}

export const AUDIENCE: Audience[] = [
	{
		icon: "code",
		name: "Engineers",
		label: "Stay updated with",
		items: [
			"Framework changes",
			"Releases",
			"Security alerts",
			"AI developments",
		],
	},
	{
		icon: "science",
		name: "Researchers",
		label: "Follow",
		items: [
			"Papers and publications",
			"Emerging fields",
			"Field discussions",
			"Research workflows",
		],
	},
	{
		icon: "lightbulb",
		name: "Curious minds",
		label: "Understand",
		items: ["What changed", "Why it matters", "Where things are going"],
	},
];

export interface NotAiPoint {
	icon: string;
	text: string;
}

/** "Not another AI chat window" — the four things Vorynth is built around. */
export const NOT_AI: { points: NotAiPoint[]; closing: string } = {
	points: [
		{ icon: "rss_feed", text: "Your sources" },
		{ icon: "folder_open", text: "Your archive" },
		{ icon: "history", text: "Your reading history" },
		{ icon: "psychology", text: "Your intelligence workflow" },
	],
	closing:
		"Everything is stored locally on your device \u2014 Vorynth works alongside your AI assistant, not instead of it.",
};

export interface Faq {
	q: string;
	a: string;
	/** One-line takeaway shown as a highlighted callout under the answer. */
	key?: string;
}

export const FAQ: Faq[] = [
	{
		q: "What is Vorynth?",
		a: "Vorynth is a local-first personal intelligence engine that collects information from your trusted sources, ranks what matters, and optionally uses AI to explain why it matters. It is designed for engineers, researchers, and anyone who wants to stay updated without spending hours reading everything.",
	},
	{
		q: "Why is Vorynth local-first?",
		a: "Because your information is yours. Local-first means Vorynth runs entirely on your device: collected articles, reading history, notes, sources, settings, and API keys are stored locally and stay under your control. There is no cloud account, no telemetry, and nothing is shared unless you explicitly send it to an AI provider. For researchers and organizations, keeping research data on their own machines isn\u2019t a preference \u2014 it\u2019s a requirement.",
	},
	{
		q: "Why not just use ChatGPT, Claude, or Gemini?",
		a: "Different tools, different purposes. General AI assistants are excellent for answering questions, but Vorynth is built around your own sources, your own archive, your own reading history, and your own workflow. Everything is stored locally on your device, and you choose when \u2014 or if \u2014 an AI provider is used. Some people don\u2019t want their information in big-company AI products, and many universities and organizations can\u2019t allow research data to be shared with them. Certifications like SOC 2 reduce risk, but they can never give you certainty about how your data is used. Vorynth removes the question: your data never leaves your device unless you send it.",
		key: "Your data never leaves your device.",
	},
	{
		q: "Does Vorynth replace AI assistants?",
		a: "No. Vorynth works alongside AI assistants. Think of it as your personal information layer: sources in, understanding out. AI assistants answer questions; Vorynth helps you know which questions are worth asking.",
	},
	{
		q: "Do I need an AI API key?",
		a: "No \u2014 Vorynth works without one, but a key unlocks the features that make it really useful. **News mode needs no API key: collect, rank, read, search, and archive \u2014 all on your device.** Add your own provider key and the advanced features turn on \u2014 **translations, AI summaries (why it matters, impact, recommended action), plain-language questions with citations, and the Behavior Summary.** Supported providers: Gemini, OpenAI, Anthropic, and Ollama. Without a key, Vorynth is a clean, private news reader; with one, it explains and translates for you.",
		key: "News mode: no key. Intelligence mode: optional.",
	},
	{
		q: "Where is my data stored?",
		a: "On your machine. Vorynth stores collected articles, reading history, notes, sources, settings, and API keys locally. There is no mandatory account and no required cloud synchronization.",
		key: "No mandatory account, no required cloud sync.",
	},
	{
		q: "Can universities or researchers use Vorynth?",
		a: "Yes. Vorynth was partly shaped by conversations around research workflows. Researchers can follow papers, track developments in their field, monitor new trends, and organize knowledge. Because Vorynth is local-first, universities and research groups keep full control over their collected information \u2014 research data doesn\u2019t enter a third-party AI product unless they opt in.",
		key: "Research data stays under your control.",
	},
	{
		q: "Is Vorynth only for software engineers?",
		a: "No. Software engineering is the starting point, because that\u2019s where Vorynth was born. The architecture supports other domains \u2014 research, science, security, finance, medicine, and any field with reliable information sources.",
	},
	{
		q: "Does Vorynth scrape websites?",
		a: "Vorynth prefers legitimate public sources: RSS feeds, public APIs, sitemaps, and public JSON endpoints. Official connectors are built only for sources with a legitimate public access path, and community connectors can extend support for additional sources.",
	},
	{
		q: "Is Vorynth open source?",
		a: "Yes. The source code is available under the MIT license. You can inspect how the application works, build from source, and contribute improvements.",
	},
	{
		q: "Can I backup or delete my data?",
		a: "Yes. Your data belongs to you. You can back up your local database, restore your data, and delete your collected information \u2014 no account required.",
	},
	{
		q: "Is there a mobile version?",
		a: "Not yet \u2014 Vorynth is a desktop app. We have no plan for phone support at the moment, but it will likely be added in the future.",
	},
];

export interface WhyItem {
	icon: string;
	title: string;
	body: string;
}

export const WHY: WhyItem[] = [
	{
		icon: "radar",
		title: "Signal over noise",
		body: "The goal isn\u2019t collecting everything \u2014 it\u2019s finding what matters. Every story is importance-ranked, not just time-sorted.",
	},
	{
		icon: "fact_check",
		title: "Explain, don't just summarize",
		body: "A summary answers \u201cwhat happened?\u201d Vorynth answers what happened, why it matters, and what to do about it.",
	},
	{
		icon: "verified",
		title: "Source quality over quantity",
		body: "A handful of sources you trust beats a thousand you don\u2019t. Curated lists and per-source controls keep the noise out.",
	},
	{
		icon: "lock",
		title: "Private by design",
		body: "Local-first storage, no account, no telemetry. Your sources, history, and keys never leave your machine.",
	},
];

export interface Step {
	icon: string;
	step: string;
	title: string;
	body: string;
}

export const STEPS: Step[] = [
	{
		icon: "rss_feed",
		step: "Step 1 \u00b7 Collect",
		title: "Your sources, fetched",
		body: "Six adapters \u2014 RSS, GitHub releases, arXiv, HTML crawling, Sitemaps, and JSON APIs \u2014 plus curated lists you enable in one click.",
	},
	{
		icon: "filter_alt",
		step: "Step 2 \u00b7 Normalize & rank",
		title: "Signal floats up",
		body: "Every item is deduplicated, classified, and importance-scored \u2014 so the stories that matter today sit on top, not the noisiest feed.",
	},
	{
		icon: "psychology",
		step: "Step 3 \u00b7 Understand",
		title: "Why it matters",
		body: "The AI triad \u2014 why it matters, impact, and a recommended action \u2014 generated from your choice of four LLM providers.",
	},
	{
		icon: "campaign",
		step: "Step 4 \u00b7 Deliver",
		title: "A brief you own",
		body: "Skim the daily brief in minutes, search everything, ask questions with citations, and file it all in your archive \u2014 all on-device.",
	},
];

export interface Mode {
	featured: boolean;
	tone: "news" | "ai";
	tag: string;
	title: string;
	desc: string;
	bullets: string[];
}

export const MODES: Mode[] = [
	{
		featured: false,
		tone: "news",
		tag: "News mode \u00b7 no key",
		title: "A ranked feed that just works",
		desc: "Vorynth collects, ranks, and serves a clean brief with zero configuration \u2014 no API key required, ever.",
		bullets: [
			"Importance-ranked feed from your sources",
			"Search, archive, and backups included",
			"Fully offline once sources are collected",
		],
	},
	{
		featured: true,
		tone: "ai",
		tag: "Intelligence mode \u00b7 optional",
		title: "Add the AI triad any time",
		desc: "Bring your own API key and Vorynth explains each story \u2014 why it matters, its impact, and a recommended action.",
		bullets: [
			"Why it matters / Impact / Recommended action per story",
			"Ask questions in plain language, answered with citations",
			"Four providers: OpenAI, Anthropic, Gemini, Ollama",
		],
	},
];

export interface Stat {
	icon: string;
	value: string;
	label: string;
}

export const STATS: Stat[] = [
	{ icon: "rss_feed", value: "25", label: "Curated Feeds in the Starter List" },
	{ icon: "hub", value: "6", label: "Source Adapters" },
	{ icon: "smart_toy", value: "4", label: "LLM Providers" },
	{ icon: "shield", value: "100%", label: "Local & Private" },
];

export interface Platform {
	icon: string;
	name: string;
	status: string;
	tone: "native" | "source";
	/** Maps to a release-asset filter; "harmony" has no native installer. */
	key: PlatformKey | "harmony";
}

export const PLATFORMS: Platform[] = [
	{
		icon: "desktop_mac",
		name: "macOS",
		status: "Apple Silicon + Intel",
		tone: "native",
		key: "mac",
	},
	{
		icon: "window",
		name: "Windows",
		status: "x86_64 + ARM64",
		tone: "native",
		key: "windows",
	},
	{
		icon: "terminal",
		name: "Linux",
		status: "x86_64 + ARM64",
		tone: "native",
		key: "linux",
	},
	{
		icon: "dns",
		name: "FreeBSD",
		status: "x86_64",
		tone: "native",
		key: "freebsd",
	},
	{
		icon: "globe",
		name: "Harmony OS",
		status: "Experimental \u00b7 raw bundle",
		tone: "source",
		key: "harmony",
	},
];
