/**
 * Icon Pack (v1.8.0) — the core offline icon + font plugin.
 *
 * Registers three icon sets (Lucide, Font Awesome Solid + Brands) and 18 font
 * families (Vorynth's own Newsreader/Geist, popular Latin fonts, and fonts for
 * Persian/Arabic, Hebrew, Devanagari, Thai, Japanese, Chinese, and Korean) into
 * the host's asset registry at load time — everything served from
 * `/plugins/icons/…`, fully offline. Any other plugin consumes them through the
 * SDK (`registerIconSet`, `registerFont`, the `<Icon>` component,
 * `useAvailableFonts`); the built-in view at `/plugin/icons` is the gallery that
 * proves it: a searchable icon grid across all three sets plus a font preview.
 *
 * The data files are generated by `scripts/build-icons-assets.mjs` into
 * `public/plugins/icons/` (gitignored) — nothing is fetched from the network.
 */
import {
	useTranslation,
	Icon as SdkIcon,
	registerIconSet,
	registerFontCatalog,
	useAssetRegistry,
	useAvailableFonts,
	useState,
	useEffect,
	type PluginViewComponent,
} from "@vorynth/plugin-host";
import type {
	DocsSection,
	FontCatalog,
	IconSetData,
	IconSetId,
} from "@vorynth/types";

// ── Offline asset registration (runs once, as early as possible) ────────────

async function fetchJson<T>(url: string): Promise<T> {
	const res = await fetch(url);
	if (!res.ok) throw new Error(`${url}: HTTP ${res.status}`);
	return (await res.json()) as T;
}

let assetsLoaded = false;

async function loadOfflineAssets() {
	if (assetsLoaded) return;
	assetsLoaded = true;
	try {
		const [lucide, faSolid, faBrands, fonts] = await Promise.all([
			fetchJson<IconSetData>("/plugins/icons/icons.lucide.json"),
			fetchJson<IconSetData>("/plugins/icons/icons.fa-solid.json"),
			fetchJson<IconSetData>("/plugins/icons/icons.fa-brands.json"),
			fetchJson<FontCatalog>("/plugins/icons/fonts/fonts.json"),
		]);
		registerIconSet("lucide", lucide);
		registerIconSet("fa-solid", faSolid);
		registerIconSet("fa-brands", faBrands);
		registerFontCatalog(fonts);

		// Inject the offline @font-face rules (same family names as the CDN
		// fonts, unicode ranges kept) — the whole app renders offline once this
		// core plugin loads.
		const cssRes = await fetch("/plugins/icons/fonts/fonts.css");
		if (!cssRes.ok) throw new Error(`fonts.css: HTTP ${cssRes.status}`);
		const css = await cssRes.text();
		let style = document.getElementById(
			"vorynth-icons-fonts",
		) as HTMLStyleElement | null;
		if (!style) {
			style = document.createElement("style");
			style.id = "vorynth-icons-fonts";
			document.head.appendChild(style);
		}
		style.textContent = css;
	} catch (err) {
		console.warn("[icons] failed to register offline assets:", err);
	}
}

// Fire at module load — before any view renders, so other plugins (and the
// app's own fonts) already see the pack.
void loadOfflineAssets();

// ── Gallery view at /plugin/icons ────────────────────────────────────────────

const SET_TABS: { id: IconSetId; label: string }[] = [
	{ id: "lucide", label: "Lucide" },
	{ id: "fa-solid", label: "Font Awesome Solid" },
	{ id: "fa-brands", label: "Font Awesome Brands" },
];

const VIEW_GRID = 400;

const View: PluginViewComponent = function IconPackView() {
	const { t } = useTranslation();
	const registry = useAssetRegistry();
	const fonts = useAvailableFonts();
	const [tab, setTab] = useState<IconSetId | "fonts">("lucide");
	const [query, setQuery] = useState("");
	const [copied, setCopied] = useState<string | null>(null);

	const q = query.trim().toLowerCase();
	const setData = tab === "fonts" ? null : registry.iconSet(tab);
	const allNames = setData ? Object.keys(setData.icons) : [];
	const filtered = q ? allNames.filter((n) => n.includes(q)) : allNames;
	const visible = filtered.slice(0, VIEW_GRID);
	const count = setData ? Object.keys(setData.icons).length : 0;

	useEffect(() => {
		if (!copied) return;
		const timer = setTimeout(() => setCopied(null), 1200);
		return () => clearTimeout(timer);
	}, [copied]);

	const copyUsage = (name: string) => {
		const snippet = `<Icon set="${tab}" name="${name}" />`;
		void navigator.clipboard?.writeText(snippet).catch(() => undefined);
		setCopied(name);
	};

	return (
		<div className="space-y-6">
			<div className="rounded-lg border border-outline-variant bg-surface-container-low p-6">
				<p className="font-headline text-headline-sm text-on-surface">
					{t("icons.galleryTitle")}
				</p>
				<p className="mt-1 font-body text-body-md text-on-surface-variant">
					{t("icons.gallerySubtitle")}
				</p>
			</div>

			<div className="flex flex-wrap items-center gap-2">
				{SET_TABS.map((s) => {
					const set = registry.iconSets[s.id];
					return (
						<TabButton
							key={s.id}
							active={tab === s.id}
							label={`${s.label} (${set ? Object.keys(set.icons).length : "…"})`}
							onClick={() => setTab(s.id)}
						/>
					);
				})}
				<TabButton
					active={tab === "fonts"}
					label={`${t("icons.fontsTab")} (${fonts.length})`}
					onClick={() => setTab("fonts")}
				/>
			</div>

			<label className="block">
				<span className="sr-only">{t("icons.searchLabel")}</span>
				<input
					type="search"
					value={query}
					onChange={(e) => setQuery(e.target.value)}
					placeholder={t("icons.searchPlaceholder")}
					aria-label={t("icons.searchLabel")}
					className="w-full max-w-md rounded border border-outline-variant bg-surface-container-low px-3 py-2 font-body text-body-md text-on-surface placeholder:text-on-surface-variant focus:border-primary focus:outline-none"
				/>
			</label>

			{tab === "fonts" ? (
				<FontsGrid fonts={fonts} t={t} />
			) : !setData ? (
				<p className="font-body text-body-md text-on-surface-variant">
					{t("icons.loading")}
				</p>
			) : (
				<>
					<p className="font-label text-label-sm text-on-surface-variant">
						{t("icons.showing", {
							shown: visible.length,
							total: filtered.length,
							of: count,
						})}
					</p>
					<div className="grid grid-cols-[repeat(auto-fill,minmax(96px,1fr))] gap-2">
						{visible.map((name) => (
							<IconTile
								key={name}
								set={tab}
								name={name}
								copied={copied === name}
								onCopy={() => copyUsage(name)}
							/>
						))}
					</div>
					{filtered.length > VIEW_GRID ? (
						<p className="font-label text-label-sm text-on-surface-variant">
							{t("icons.truncated", { limit: VIEW_GRID })}
						</p>
					) : null}
					{filtered.length === 0 ? (
						<p className="font-body text-body-md text-on-surface-variant">
							{t("icons.empty")}
						</p>
					) : null}
				</>
			)}
		</div>
	);
};

function TabButton({
	active,
	label,
	onClick,
}: {
	active: boolean;
	label: string;
	onClick: () => void;
}) {
	return (
		<button
			type="button"
			onClick={onClick}
			aria-pressed={active}
			className={`rounded border px-3 py-1 font-label text-label-sm uppercase tracking-wide transition-colors ${
				active
					? "border-primary bg-primary text-on-primary"
					: "border-outline-variant text-on-surface-variant hover:border-primary"
			}`}
		>
			{label}
		</button>
	);
}

function IconTile({
	set,
	name,
	copied,
	onCopy,
}: {
	set: string;
	name: string;
	copied: boolean;
	onCopy: () => void;
}) {
	return (
		<button
			type="button"
			onClick={onCopy}
			aria-label={`${name} — click to copy the SDK snippet`}
			title={copied ? "Copied!" : `${name} (${set})`}
			className="flex flex-col items-center gap-1.5 rounded border border-outline-variant bg-surface-container-lowest p-3 text-on-surface-variant transition-colors hover:border-primary hover:text-on-surface"
		>
			<SdkIcon set={set} name={name} size={28} />
			<span className="w-full truncate text-center font-mono text-mono-technical text-[10px]">
				{copied ? "✓" : name}
			</span>
		</button>
	);
}

function FontsGrid({
	fonts,
	t,
}: {
	fonts: {
		family: string;
		script: string;
		weights: string[];
		styles: string[];
		sample: string;
	}[];
	t: (key: string, opts?: Record<string, unknown>) => string;
}) {
	if (fonts.length === 0) {
		return (
			<p className="font-body text-body-md text-on-surface-variant">
				{t("icons.loading")}
			</p>
		);
	}
	return (
		<div className="space-y-2">
			{fonts.map((f) => (
				<div
					key={f.family}
					className="rounded-lg border border-outline-variant bg-surface-container-low px-4 py-3"
				>
					<div className="flex flex-wrap items-baseline gap-x-3 gap-y-1">
						<span className="font-label text-label-md text-on-surface">
							{f.family}
						</span>
						<span className="font-mono text-mono-technical text-on-surface-variant">
							{f.weights.join(", ")} · {f.styles.join(", ")}
						</span>
						<span className="font-mono text-mono-technical text-on-surface-variant">
							{f.script}
						</span>
					</div>
					<p
						className="mt-1 font-body text-body-lg text-on-surface"
						style={{ fontFamily: `'${f.family}', sans-serif` }}
					>
						{f.sample}
					</p>
				</div>
			))}
		</div>
	);
}

// ── Docs section: the plugin's own guide ─────────────────────────────────────

const DOCS: DocsSection = {
	id: "icons",
	title: "Icon Pack",
	summary:
		"The offline icon sets and fonts that ship with Vorynth — and how any plugin consumes them through the SDK.",
	icon: "category",
	pageRoute: "/plugin/icons",
	blocks: [
		{
			type: "paragraph",
			text: "The Icon Pack is a core plugin that bundles three complete icon sets and 18 font families into the app — fully offline. Other plugins register and render them through the plugin SDK, so a plugin's UI never needs the network for icons or fonts.",
		},
		{
			type: "features",
			items: [
				{
					icon: "category",
					label: "Three icon sets",
					text: "Lucide (1,999), Font Awesome Solid (2,001) and Font Awesome Brands (609) — kebab-case names, searchable in the gallery at /plugin/icons.",
				},
				{
					icon: "font_download",
					label: "18 font families",
					text: "Vorynth's own Newsreader + Geist, popular Latin fonts (Inter, Roboto, Lora, Open Sans, Montserrat, Poppins, JetBrains Mono), Material Symbols, and Persian/Arabic, Hebrew, Devanagari, Thai, Japanese, Chinese, and Korean script fonts.",
				},
				{
					icon: "code",
					label: "SDK access",
					text: "registerIconSet, registerFont, the <Icon> component, and useAvailableFonts — all from @vorynth/plugin-host.",
				},
				{
					icon: "offline_pin",
					label: "Offline by design",
					text: "Everything ships in the app — the fonts load from the bundle, never from the network. The pack is always on: Vorynth's own icons and fonts depend on it, so it has no on/off switch and no CDN fallback.",
				},
			],
		},
		{
			type: "flow",
			title: "A plugin consumes the pack by",
			steps: [
				{ icon: "code", label: "importing from @vorynth/plugin-host" },
				{ icon: "category", label: "rendering <Icon set name />" },
				{ icon: "offline_pin", label: "working offline" },
			],
		},
		{
			type: "bullets",
			items: [
				"Icon names are kebab-case (lucide home, fa-solid house, fa-brands github). Find any name with the search in the gallery.",
				"registerIconSet / registerFontCatalog are called by the pack itself at load — other plugins only read via <Icon>, useAvailableFonts, and useAssetRegistry.",
				"Data files are generated at build time (scripts/build-icons-assets.mjs) into public/plugins/icons/ and served by the app — nothing is fetched over the network.",
			],
		},
	],
};

// ── Exports — the host's contribution contract ─────────────────────────────

export default View;
export { DOCS as docsSection };
