/**
 * AUTO-GENERATED from sources/developer.json — DO NOT EDIT BY HAND.
 * Regenerate with: node apps/core-engine/scripts/generate-seed.mjs
 *
 * The official "developer" source list. sources/developer.json is the single
 * source of truth (also served from the GitHub catalog); this module is the
 * build-time-bundled seed — ncc inlines it into the engine sidecar so the
 * official sources ship inside the app, offline.
 */
import type { SeedSource, SourceListSeed } from "./ddl.js";

export const DEVELOPER_SEED_LIST: SourceListSeed = {
	id: "developer",
	name: "Developer & Software Engineering",
	description:
		"The official Vorynth starter list — 24 stable feeds across AI, programming languages, web development, backend, devops, cloud, security and open source.",
	origin: "official",
	nsfw: false,
	version: null,
};

export const DEVELOPER_SEED_SOURCES: SeedSource[] = [
	{
		id: "src-openai-blog",
		name: "OpenAI Blog",
		url: "https://openai.com/blog/rss.xml",
		type: "rss",
		category: "ai",
		adapter: "rss",
		configuration: { feedUrl: "https://openai.com/blog/rss.xml" },
		listId: "developer",
		country: "US",
		city: "San Francisco",
		language: "en",
	},
	{
		id: "src-huggingface",
		name: "Hugging Face Blog",
		url: "https://huggingface.co/blog/feed.xml",
		type: "rss",
		category: "ai",
		adapter: "rss",
		configuration: { feedUrl: "https://huggingface.co/blog/feed.xml" },
		listId: "developer",
		country: "US",
		city: "New York",
		language: "en",
	},
	{
		id: "src-github-blog",
		name: "The GitHub Blog",
		url: "https://github.blog/feed/",
		type: "rss",
		category: "software-engineering",
		adapter: "rss",
		configuration: { feedUrl: "https://github.blog/feed/" },
		listId: "developer",
		country: "US",
		city: "San Francisco",
		language: "en",
	},
	{
		id: "src-martin-fowler",
		name: "Martin Fowler",
		url: "https://martinfowler.com/feed.atom",
		type: "rss",
		category: "software-engineering",
		adapter: "rss",
		configuration: { feedUrl: "https://martinfowler.com/feed.atom" },
		listId: "developer",
		country: "GB",
		city: "London",
		language: "en",
	},
	{
		id: "src-web-dev",
		name: "web.dev",
		url: "https://web.dev/feed.xml",
		type: "rss",
		category: "web-development",
		adapter: "rss",
		configuration: { feedUrl: "https://web.dev/feed.xml" },
		listId: "developer",
		country: "US",
		city: "Mountain View",
		language: "en",
	},
	{
		id: "src-cloudflare",
		name: "Cloudflare Blog",
		url: "https://blog.cloudflare.com/rss/",
		type: "rss",
		category: "backend",
		adapter: "rss",
		configuration: { feedUrl: "https://blog.cloudflare.com/rss/" },
		listId: "developer",
		country: "US",
		city: "San Francisco",
		language: "en",
	},
	{
		id: "src-hashicorp",
		name: "HashiCorp Blog",
		url: "https://www.hashicorp.com/blog/feed.xml",
		type: "rss",
		category: "devops",
		adapter: "rss",
		configuration: { feedUrl: "https://www.hashicorp.com/blog/feed.xml" },
		listId: "developer",
		country: "US",
		city: "San Francisco",
		language: "en",
	},
	{
		id: "src-aws",
		name: "AWS News Blog",
		url: "https://aws.amazon.com/blogs/aws/feed/",
		type: "rss",
		category: "cloud",
		adapter: "rss",
		configuration: { feedUrl: "https://aws.amazon.com/blogs/aws/feed/" },
		listId: "developer",
		country: "US",
		city: "Seattle",
		language: "en",
	},
	{
		id: "src-krebs",
		name: "Krebs on Security",
		url: "https://krebsonsecurity.com/feed/",
		type: "rss",
		category: "security",
		adapter: "rss",
		configuration: { feedUrl: "https://krebsonsecurity.com/feed/" },
		listId: "developer",
		country: "US",
		city: "Arlington",
		language: "en",
	},
	{
		id: "src-cloudflare-security",
		name: "Cloudflare Security",
		url: "https://blog.cloudflare.com/tag/security/rss/",
		type: "rss",
		category: "security",
		adapter: "rss",
		configuration: { feedUrl: "https://blog.cloudflare.com/tag/security/rss/" },
		listId: "developer",
		country: "US",
		city: "San Francisco",
		language: "en",
	},
	{
		id: "src-openssf",
		name: "OpenSSF Blog",
		url: "https://openssf.org/feed/",
		type: "rss",
		category: "open-source",
		adapter: "rss",
		configuration: { feedUrl: "https://openssf.org/feed/" },
		listId: "developer",
		country: "US",
		city: "San Francisco",
		language: "en",
	},
	{
		id: "src-rust",
		name: "Rust Blog",
		url: "https://blog.rust-lang.org/feed.xml",
		type: "rss",
		category: "programming-languages",
		adapter: "rss",
		configuration: { feedUrl: "https://blog.rust-lang.org/feed.xml" },
		listId: "developer",
		country: "US",
		city: null,
		language: "en",
	},
	{
		id: "src-python",
		name: "Python Insider",
		url: "https://pythoninsider.blogspot.com/feeds/posts/default",
		type: "rss",
		category: "programming-languages",
		adapter: "rss",
		configuration: {
			feedUrl: "https://pythoninsider.blogspot.com/feeds/posts/default",
		},
		listId: "developer",
		country: "US",
		city: null,
		language: "en",
	},
	{
		id: "src-go-blog",
		name: "The Go Blog",
		url: "https://go.dev/blog/feed.atom",
		type: "rss",
		category: "programming-languages",
		adapter: "rss",
		configuration: { feedUrl: "https://go.dev/blog/feed.atom" },
		listId: "developer",
		country: "US",
		city: "Mountain View",
		language: "en",
	},
	{
		id: "src-nodejs",
		name: "Node.js Blog",
		url: "https://nodejs.org/en/feed/blog.xml",
		type: "rss",
		category: "web-development",
		adapter: "rss",
		configuration: { feedUrl: "https://nodejs.org/en/feed/blog.xml" },
		listId: "developer",
		country: "US",
		city: "San Francisco",
		language: "en",
	},
	{
		id: "src-react",
		name: "React Blog",
		url: "https://react.dev/feed.xml",
		type: "rss",
		category: "web-development",
		adapter: "rss",
		configuration: { feedUrl: "https://react.dev/feed.xml" },
		listId: "developer",
		country: "US",
		city: "San Francisco",
		language: "en",
	},
	{
		id: "src-vercel",
		name: "Vercel Blog",
		url: "https://vercel.com/blog/rss.xml",
		type: "rss",
		category: "web-development",
		adapter: "rss",
		configuration: { feedUrl: "https://vercel.com/blog/rss.xml" },
		listId: "developer",
		country: "US",
		city: "San Francisco",
		language: "en",
	},
	{
		id: "src-simon-willison",
		name: "Simon Willison",
		url: "https://simonwillison.net/atom/everything/",
		type: "rss",
		category: "ai",
		adapter: "rss",
		configuration: { feedUrl: "https://simonwillison.net/atom/everything/" },
		listId: "developer",
		country: "GB",
		city: "London",
		language: "en",
	},
	{
		id: "src-jvns",
		name: "Julia Evans",
		url: "https://jvns.ca/atom.xml",
		type: "rss",
		category: "devops",
		adapter: "rss",
		configuration: { feedUrl: "https://jvns.ca/atom.xml" },
		listId: "developer",
		country: "CA",
		city: "Montreal",
		language: "en",
	},
	{
		id: "src-smashing",
		name: "Smashing Magazine",
		url: "https://www.smashingmagazine.com/feed/",
		type: "rss",
		category: "web-development",
		adapter: "rss",
		configuration: { feedUrl: "https://www.smashingmagazine.com/feed/" },
		listId: "developer",
		country: "DE",
		city: "Freiburg",
		language: "en",
	},
	{
		id: "src-aws-security",
		name: "AWS Security Blog",
		url: "https://aws.amazon.com/blogs/security/feed/",
		type: "rss",
		category: "security",
		adapter: "rss",
		configuration: { feedUrl: "https://aws.amazon.com/blogs/security/feed/" },
		listId: "developer",
		country: "US",
		city: "Seattle",
		language: "en",
	},
	{
		id: "src-ms-devblogs",
		name: "Microsoft Developer Blogs",
		url: "https://devblogs.microsoft.com/feed/",
		type: "rss",
		category: "software-engineering",
		adapter: "rss",
		configuration: { feedUrl: "https://devblogs.microsoft.com/feed/" },
		listId: "developer",
		country: "US",
		city: "Redmond",
		language: "en",
	},
	{
		id: "src-google-ai",
		name: "Google AI Blog",
		url: "https://blog.google/technology/ai/rss/",
		type: "rss",
		category: "ai",
		adapter: "rss",
		configuration: { feedUrl: "https://blog.google/technology/ai/rss/" },
		listId: "developer",
		country: "US",
		city: "Mountain View",
		language: "en",
	},
	{
		id: "src-netflix-tech",
		name: "Netflix TechBlog",
		url: "https://netflixtechblog.com/feed",
		type: "rss",
		category: "software-engineering",
		adapter: "rss",
		configuration: { feedUrl: "https://netflixtechblog.com/feed" },
		listId: "developer",
		country: "US",
		city: "Los Gatos",
		language: "en",
	},
];
